### ISSUE TITLE
Is there any plan for supporting realm?

### ISSUE THREAD

**Issue by xilin** [Flipboard/FLEX#100]
[Realm](https://realm.io) is a new database for mobile device. Is there any plan to support viewing the db file of Realm in the future? Thanks.

**Comment by ryanolsonk** [comment]
I don't personally have plans to build support, but it would be awesome if someone else wanted to pick this up!

**Comment by Terry174** [comment]
Consider using [RealmBrowser](https://github.com/realm/realm-browser-osx) as viewing Realm databases is the intention of this project. Also be aware that including Realm is quite a large dependency to add to FLEX, seeing it doesn't currently require any third-party dependencies (AFAIK).

**Comment by nin9tyfour** [comment]
Consider using RealmBrowser as viewing Realm databases is the intention of this project. Also be aware that including Realm is quite a large dependency to add to FLEX, seeing it doesn't currently require any third-party dependencies (AFAIK).

**Comment by TimOliver** [comment]
Greetings everyone! Crazily enough, I actually had the same idea and came here to discover someone had already beaten me to suggesting it!

This was something I also wanted to see in FLEX (I use it quite a lot to debug one of my side project apps), so I took the time last weekend to add Realm integration and just pushed it as a PR: https://github.com/Flipboard/FLEX/pull/105

I was also very wary, as @nin9tyfour pointed out that requiring Realm as an explicitly-included dependency would be terrible. So the code is presented in an optional macro that is only included if the Realm framework is present in the project itself when FLEX is built.

In any case, let me know if you have any queries about it.

**Full Disclosure:** I am an employee of Realm (My main project is the Realm Browser), but as we are not presently in a position to offer official support for third party Realm integrations, I'm providing this as an unofficial project. I'm happy to assist with any queries in my spare time. :)

**Comment by xilin** [comment]
@TimOliver That's great! Thanks for your work!

**Comment by khoren93** [comment]
@TimOliver Thanks:)

**Comment by ryanolsonk** [comment]
This is now on master :smile:
