### ISSUE TITLE
Is it possible to enable "Network Debugging" by default?

### ISSUE THREAD

**Issue by kccheung** [Flipboard/FLEX#101]
As title, so that user no need to toggle it every time upon a fresh install of an app supported with FLEX.

**Comment by ryanolsonk** [comment]
Yep! You can use the API on `FLEXManager`: https://github.com/Flipboard/FLEX/blob/master/Classes/ExplorerToolbar/FLEXManager.h#L27

**Comment by sietec** [comment]
> Yep! You can use the API on `FLEXManager`: https://github.com/Flipboard/FLEX/blob/master/Classes/ExplorerToolbar/FLEXManager.h#L27

This is a dead link...I'm going to try to find the correct, newest version, and will add a response here if i find it...

**Comment by sietec** [comment]
found it:

[FlexManager.h Line 27](https://github.com/Flipboard/FLEX/blob/8367342b25e963d8d0110a9979f0c853e2550c7c/Classes/FLEXManager.h#L37)

**Comment by NSExceptional** [comment]
Be aware that this property will be moved to another file in 4.0

**Comment by sietec** [comment]
Thanks for the heads up 👌🏼

**Comment by lis186** [comment]
`UserDefaults.standard.set(1, forKey: "com.flex.FLEXNetworkObserver.enableOnLaunch")`
