### ISSUE TITLE
Unrecognized Selector crash in iOS 8 ([UITouch maximumPossibleForce:])

### ISSUE THREAD

**Issue by adamatimvu** [Flipboard/FLEX#103]
in FLEXKeyboardShortcutManager.m, line 168
```
double adjustedPressureLevel = pressureLevel * 20 * touch.maximumPossibleForce;
```
`maximumPossibleForce` is iOS 9 and above  ;(

Using FLEX 2.2.0 via CocoaPods, repros easily by launching iOS 8.4 simulator and pressing cmd+ctrl+shift together while tapping mouse.

**Comment by ryanolsonk** [comment]
Fixed in bd821dc553a837c4c9f46226a3192e8d4dbc1f4c
