### ISSUE TITLE
iOS 8 simulator crashing when entering text

### ISSUE THREAD

**Issue by orenco82** [Flipboard/FLEX#113]
Hi,

I'm experiencing a crash when debugging my app with the iOS 8 simulator, when entering text with the iOS onscreen keyboard (happens in the first character).
I'm getting ```EXC_BAD_ACCESS``` in ```keyCode = [event _keyCode];``` at the ```handleKeyboardEvent``` function in the FLEXKeyboardShortcutManager.m class.

Thanks in advance!
Oren

**Comment by orenco82** [comment]
(iOS 8.4 simulator in Xcode 7.2.1) , doesn't happen in iOS 9 simulator.

**Comment by Munchery-KleinLieu** [comment]
Happens to me in my iOS 9 sim. Got around it by turning off the method swizzling happening on keyboard shortcuts via: `[[FLEXManager sharedManager] setSimulatorShortcutsEnabled:NO];`

**Comment by ryanolsonk** [comment]
I believe this was fixed on master a few weeks ago. I'll do a release soon to make sure everyone gets the fix.

**Comment by orenco82** [comment]
Thanks @ryanolsonk , that would be great.
Went with the ```[[FLEXManager sharedManager] setSimulatorShortcutsEnabled:NO];``` fix in the meantime.

**Comment by ryanolsonk** [comment]
This was actually a different issue that what I thought. Fixed in 24985ac9842f22b1609e296a286f61f7d4a352db
