### ISSUE TITLE
3D Touch - Peek and Pop

### ISSUE THREAD

**Issue by Hacoga** [Flipboard/FLEX#115]
Hi, first thank you so much for this is amazing! :+1: 

Excuse me! amm the Peek and Pop it does not work on Simulator 6s plus with Xcode 7.2 when I´m doing the longer press and use the combination of the command, control, and shift ... can you tell me why? 

Thanks!
Regards!

**Comment by Romza** [comment]
I have the same problem. Peek and Pop doesn't work with Xcode 7.2, I tried iOS 9.1 and 9.2 on various iPhone simulators.

**Comment by ryanolsonk** [comment]
One important part about the force touch support is that the touch needs to move to get force updates. Can you try moving the touch slightly after pressing command + control + shift? It's still working for me on Xcode 7.2.

I realize this isn't ideal behavior, but the feature is really just a stopgap until Apple provides actual support for force touch directly in the simulator.

**Comment by felixwcf** [comment]
It works on my Xcode 7.2.1 and iPhone 6S simulator. Just like @ryanolsonk said, you need to move a bit of your mouse cursor to let it work while holding Shift + Command, **not** Command + Control + Shift.

**Comment by ryanolsonk** [comment]
I will probably remove this feature now that Apple supports it in the simulator on machines with force-touch trackpads.
