### ISSUE TITLE
How do i run on iPod 5,1 iOS 9.2.1

### ISSUE THREAD

**Issue by memlojr** [Flipboard/FLEX#122]
I am having trouble sideloading FLEX through xcode

**Comment by mitchellporter** [comment]
I'm using `Flipboard FLEX Loader` on my jailbroken iPod 5. Hopefully that helps.

**Comment by memlojr** [comment]
Oh do you have to be jailbroken to use FLEX?

**Comment by mitchellporter** [comment]
No, you don't have to be jailbroken, just saying that currently works for me. The cocoapod also works for me on my normal iPhone.

**Comment by memlojr** [comment]
Oo

**Comment by ryanolsonk** [comment]
If you would like to run FLEX in other people's apps, you will need a jailbroken phone. Otherwise you can integrate it into your own app through cocoapods, carthage, or directly. There are instructions in the readme.
