### ISSUE TITLE
Realm browser is not working with RealmSwift 0.100.0

### ISSUE THREAD

**Issue by jkim-git** [Flipboard/FLEX#125]
Says there are 0 tables - but I verified using realm browser that there is data stored in the realm file.

**Comment by ryanolsonk** [comment]
@TimOliver do you have any insight here?

**Comment by TimOliver** [comment]
Uh-oh. Not without more information!

If there's nothing private in there, can you please post the zipped up Realm file here so I can test it myself?

**Comment by ryanolsonk** [comment]
This is pretty old -- just going back through the issues now -- so perhaps it's no longer a problem.

**Comment by TimOliver** [comment]
Okay sure thing. Let me know if you need me to test/fix anything! :)
