### ISSUE TITLE
no visible @interface for 'RLMRealmConfiguration' declares the selector 'setPath:'

### ISSUE THREAD

**Issue by davidlondono** [Flipboard/FLEX#127]
I got this error when tried to complile my project, it bight be by an update of realm or something, so pleas check out what could you do to fix it

**Comment by rubikva** [comment]
I have the same problem too ...

**Comment by davidlondono** [comment]
I'm using an older version of Realm.... but thats not the idea....

**Comment by TimOliver** [comment]
Hi guys! I just noticed this too. Realm recently changed its API to use `NSURL` instead of strings when referring to file paths. In the very latest release, the old `path` properties were deprecated and subsequently removed. 

I'll make a pull request to fix this ASAP!

**Comment by idream97** [comment]
I'm using Flex from cocoapods. Please update cocoapods too.

**Comment by idream97** [comment]
I'm using Flex from cocoapods. Please update cocoapods too.

**Comment by lakhman** [comment]
👍  for cocoapods update, for now you can use the master or a specific commit like so:

```
# Use master branch
pod 'FLEX', :git => 'https://github.com/Flipboard/FLEX.git'

# Use the latest commit (which includes this fix)
pod 'FLEX', :git => 'https://github.com/Flipboard/FLEX.git', :commit => 'c766e5d'
```

**Comment by ryanolsonk** [comment]
Will do a version bump shortly.

**Comment by ryanolsonk** [comment]
Latest release has this now. Sorry for the delay.
