### ISSUE TITLE
How to exclude FLEX.framework from release builds?

### ISSUE THREAD

**Issue by coppercash** [Flipboard/FLEX#131]
Hi,
I have read the section **Excluding FLEX from Release (App Store) Builds** in the README, which suggests to exclude source files by name.
However, I am using **FLEX.framework** with the form of **Embedded Binaries**.
Is there any way to exclude **FLEX.framework** from release builds?
Thanks

**Comment by ryanolsonk** [comment]
You should be able to do something like `-framework FLEX.framework` in the **Other Linker Flags** build setting. I haven't looked into specifics, hopefully that sets you on the right path.
