### ISSUE TITLE
System log messages no longer displayed on iOS 10

### ISSUE THREAD

**Issue by andreyz** [Flipboard/FLEX#140]
On iOS 10 betas 1-4 no log messages are displayed. Probably due to introduced [Unified Logging and Activity Tracing](https://developer.apple.com/videos/play/wwdc2016/721/)?

**Comment by ryanolsonk** [comment]
Yea, it looks like ASL has been replaced by OS Log. We'll need to provide conditional support for iOS 10+.

**Comment by coderyi** [comment]
I also have this problem ，hope to resolve this

**Comment by LittleChuan** [comment]
Same problem.

**Comment by gjterry** [comment]
same problem

**Comment by Huang-Libo** [comment]
Looking forward to the enhancement

**Comment by pashaisthebest** [comment]
Same problem

**Comment by neghao** [comment]
Same problem

**Comment by riverlj** [comment]
Same problem

**Comment by TristenChenTao** [comment]
Same problem

**Comment by iunion** [comment]
Same problem with iphone7/p, but iphone6/p can output logs.

**Comment by CodeLife2012** [comment]
Solved?

**Comment by JustDoEat** [comment]
same problem and I use the GHConsole the repository in GitHub to solve this problem. https://github.com/Liaoworking/GHConsole

**Comment by CodeLife2012** [comment]
I have a idea and test in a simple project, maybe anyone can add it to `Flex`. Use pipes to redirect and capture `stdout` and `stderror`.

**Comment by rob2468** [comment]
[Read logs using the new swift os_log api](https://stackoverflow.com/questions/40272910/read-logs-using-the-new-swift-os-log-api)
"New APIs for searching new log data will not be made public this release".
Seems no way to query logs with new api in os/log.h.

**Comment by NSExceptional** [comment]
Is this still broken? I'm on iOS 11 and it seems to be working fine, but I am jailbroken

**Comment by AnthoPakPak** [comment]
@NSExceptional Yes it still appears to be broken for me, even on my jailbroken device (iOS 11.3.1)

**Comment by xingheng** [comment]
Same here in iOS 12.0

**Comment by PhilCai1993** [comment]
[https://github.com/facebook/react-native/blob/master/React/Profiler/RCTPerfMonitor.m#L366](url)

May be an alternative.

**Comment by NSExceptional** [comment]
Thank you! I'll look into that. This bug is killing me.

**Comment by NSExceptional** [comment]
@CodeLife2012 I don't believe NSLog writes to either of the standard outputs, so I'm not sure how useful that would be. That appears to be what the link by @PhilCai1993 is doing as well.

**Comment by codwam** [comment]
Is there any solution?
Swizzle NSLog or print method support?

**Comment by NSExceptional** [comment]
There is no way to swizzle a function. I'm looking into other means currently

**Comment by NSExceptional** [comment]
Ugh, I always forget that referencing an issue makes it pop up here.

Anyway, I've got logs working on iOS 10+, but there's a problem. OS Log doesn't provide a way to get *old* messages the way ASL does. In ASL, you could query the log like a database and get every single message since the app launched. With OS Log, it seems we have to continuously monitor it to get logs.

I'd love some feedback on what we should do about that. I'm thinking maybe monitor on launch and write the logs to a file that gets purged on the next launch? But if there's a lot of logs, it could be costly to use a simple text file for storage.

**Comment by NSExceptional** [comment]
Alright, I've finally fixed this. I've added two new classes: `FLEXASLLogController` and `FLEXOSLogController`, and FLEX will use the appropriate class based on your iOS version.

There's a caveat though. OS Log is much more limited that ASL. ASL worked transparently like a database; you could simply ask it for every log message so far and you would get them all back, and it's reasonable to assume that ASL doesn't count against your memory limit. OS Log, however, has no such API to my knowledge. You can only simply intercept messages as they come in.

So, on iOS 10+, there will be a **Settings** button in the navigation bar. If you press it, it will explain this to you and give you the option to turn what I'm calling "persistent logging" on or off. With persistent logging on, log messages will be stored in memory in the background from the moment the app launches, until it is turned off or the app closes. It defaults to off.
