### ISSUE TITLE
Can integrate this framework when release and submit to App store?

### ISSUE THREAD

**Issue by CodeLife2012** [Flipboard/FLEX#146]
Any private API used in this framework?

Or put this in a release build will cause some problems?

**Comment by mitchellporter** [comment]
You should only be using this in debug builds.

**Comment by CodeLife2012** [comment]
But why? @mitchellporter

**Comment by mitchellporter** [comment]
Here is the description for FLEX in the README: 

> FLEX (Flipboard Explorer) is a set of in-app debugging and exploration tools for iOS development. When presented, FLEX shows a toolbar that lives in a window above your application. From this toolbar, you can view and modify nearly every piece of state in your running application.

Ask yourself whether that belongs in a release build being given to beta testers or being submitted to the App Store. For em the answer has always been no.

**Comment by yanzhiwei147** [comment]
I hope use this framework when release and submit to App store, but hide when application launch, it aroused only server issued some instruct.

**Comment by ryanolsonk** [comment]
There are several apps on the store that include this framework (see http://mightysignal.com/top-ios-sdks?tag=6)

Be warned that there is private API use and your app may be rejected. I do not recommend including the tool in your production app, but it seems at least a few people have gotten it through app review.

**Comment by CodeLife2012** [comment]
nice site.
