### ISSUE TITLE
Will remove support for iOS7?

### ISSUE THREAD

**Issue by CodeLife2012** [Flipboard/FLEX#154]
I saw a commit 7afd50d24167fb3679edc6312b8507db7f98d165 has `removed asl hacks needed for iOS 7`.

**Comment by ryanolsonk** [comment]
Yes, FLEX now only supports iOS 8 and higher. I'm not sure I understand the question here. Could you clarify?

**Comment by CodeLife2012** [comment]
ReadMe still state support iOS 7 and higher, just confirm this. So close this.

**Comment by ryanolsonk** [comment]
Ah yea, we should update the readme
