### ISSUE TITLE
ATS Compliance

### ISSUE THREAD

**Issue by pavm035** [Flipboard/FLEX#158]
Hi,

We are using this SDK in one of our popular product, I feel that this SDK is just for local purpose under the hood this does not track or send anything to remote server, reason i'm asking here is to ensure that this will not be show blocker in s :pite of ATS compliance requirement at the time we release. :)

Thanks

**Comment by pavm035** [comment]
Hi @mitchellporter  

So in that case if we running the app in debug build do we still need ATS compliance check, I mean at least by adding Exception keys.

**Comment by mitchellporter** [comment]
I think you're worrying about nothing. I've never actually inspected it but I HIGHLY doubt FLEX is tracking or sending anything to a remote server. I'm so sure that I'd bet money on it. The purpose of FLEX is just a debug tool. It's not like it has any third-party plugins or calls to a FLEX web service or something.

Just don't include FLEX in your release builds and use it as a debugging tool.

**Comment by ryanolsonk** [comment]
FLEX itself does not make any network requests. As @mitchellporter said, this is just a debugging tool. Including in release builds is also not officially supported by this project as there is private API use which goes against App Store guidelines.
