### ISSUE TITLE
crash !! why? 

### ISSUE THREAD

**Issue by wenyhooo** [Flipboard/FLEX#165]
![image](https://cloud.githubusercontent.com/assets/5977236/21540989/4131b222-cdee-11e6-846a-06a183500fd5.png)

**Comment by lovesunstar** [comment]
You can try:

![image](https://cloud.githubusercontent.com/assets/2378280/21544708/6ed3f226-ce0c-11e6-9057-3a9fd284855b.png)

If you are using FLEX with dynamic lib

**Comment by diong** [comment]
debug in simulators is ok

**Comment by ryanolsonk** [comment]
It looks like they dylib isn't getting copied over to your application's bundle. The suggestion above may work, or some other change to your project set up may be required.
