### ISSUE TITLE
Adding support for gzipped data

### ISSUE THREAD

**Issue by nicked** [Flipboard/FLEX#170]
In our POST requests, we gzip the request body which unfortunately the FLEX network logger can't display.

It's trivial to add support for displaying gzipped data (~3 lines of code) using a pod like 'GZIP', but I'm not sure what the policy is on adding 3rd-party dependencies.

If it's OK to add a dependency to the pod spec, I'm happy to create a pull request with this change, but thought I'd check first.

**Comment by ryanolsonk** [comment]
We actually already support this if the response headers are set correctly:

https://github.com/Flipboard/FLEX/blob/22e7edb698a74d2b9a083eb942f1f4384a9a7c94/Classes/Network/FLEXNetworkTransactionDetailTableViewController.m#L457-L460

**Comment by ryanolsonk** [comment]
Ah -- reading again I see you're talking about the request body. Want to bring that support over to displaying the request body? Should be pretty easy since it's already separated into a utility method.

**Comment by nicked** [comment]
Ah that's easy then. I assumed NSURL* automatically decoded zipped responses so FLEX didn't need to support it at all. I'll see if I can use that for the request bodies too.

**Comment by nicked** [comment]
Actually it seems that we aren't setting the headers in the way that FLEX is expecting... if I set "Content-Encoding": "gzip" then it works OK. Which actually happens right in that snippet you posted. Thanks anyway :)
