### ISSUE TITLE
Network Debugging Problem (iOS 10.x)

### ISSUE THREAD

**Issue by barankaansert** [Flipboard/FLEX#171]
Network Debugging enable but I can not see anything on network history except fabric / crashlytics requests.The requests sends from the other framework in the workspace where the application is bound.

**Comment by ryanolsonk** [comment]
Any chance you can provide a sample project with a repro of this? If not, could you provide details about your project like language, version, etc.?

**Comment by neghao** [comment]
After  iOS 10.0，System Log Could not display

**Comment by ryanolsonk** [comment]
Closing since there's nothing actionable here. Feel free to open a new issue with added information.
