### ISSUE TITLE
Crash in `prettyArgumentComponentsForMethod:`

### ISSUE THREAD

**Issue by piotr-tobolski** [Flipboard/FLEX#186]
In method `prettyArgumentComponentsForMethod:` (FLEXRuntimeUtility.m:287)
`selectorName` is `URLSession:downloadTask:didFinishDownloadingToURL:`
`selectorComponents` has 4 elements
`method_getNumberOfArguments` returns 7
In the last iteration of the loop (`argIndex` is 6) it is trying to access `selectorComponents` element at index of 4.

This looks like an iOS issue that needs a workaround because the `numberOfArguments` is incorrect. I reproduced it on iPhone 7 Plus 10.3 simulator.

It looks like there is already PR #178 to fix this.

**Comment by ryanolsonk** [comment]
Merged #178
