### ISSUE TITLE
Learning from Other Apps

### ISSUE THREAD

**Issue by wg689** [Flipboard/FLEX#200]
how to use this to Learning from Other Apps ?

**Comment by CodeLife2012** [comment]
Learning?  Install a tweak in Cydia, need you have a jailbreak device first.

**Comment by HomlesZhao** [comment]
I use it to learn...`scp -r /Users/zwy/Desktop/libFlex.dylib   root@192.168.3.3:/Library/MobileSubstrate/DynamicLibraries` ...crash

**Comment by lanvsblue** [comment]
you can see my repo https://github.com/lanvsblue/libFlex

**Comment by faimin** [comment]
[MonkeyDev](https://github.com/AloneMonkey/MonkeyDev) is a better choice for you.
