### ISSUE TITLE
Log only specific network requests

### ISSUE THREAD

**Issue by gasparuff** [Flipboard/FLEX#216]
Right now FLEX is logging every single network call in my App, including different Google Analytics calls and other network calls from libs that I'm using. I would like to have only those requests and responses logged, that are called against the App's backend. Is there any easy way of doing that?
Thanks

EDIT:
I found out there is a blacklisting feature in the current branch, but this is not included when I install from cocoapods...

**Comment by NSExceptional** [comment]
You can specify a branch in your podfile
