### ISSUE TITLE
Unable to display SQLite correctly on iPhoneX

### ISSUE THREAD

**Issue by JonHome** [Flipboard/FLEX#225]
I cannot display correctly on iPhoneX when I view sqlite file

**Comment by NSExceptional** [comment]
Could you post a screenshot?

**Comment by AlbertWu0212** [comment]
![img_5f1cec2c132a-1](https://user-images.githubusercontent.com/7083917/42611784-7d1600aa-85ca-11e8-8293-efa48c2ae595.jpeg)
I found that problem too.
