### ISSUE TITLE
Not compiling with `use_modular_headers!` flag in PodFile

### ISSUE THREAD

**Issue by sauravexodus** [Flipboard/FLEX#230]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLEXManager", referenced from:
      objc-class-ref in MyViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Cocoapods 1.5.3
Not using `use_frameworks!` flag according to the new convention.

**Comment by zuoyou1314** [comment]
you can add debug 

#ifdef DEBUG
#import <FLEX.h>
#endif

**Comment by zuoyou1314** [comment]
you can add debug

#ifdef DEBUG
#import <FLEX.h>
#endif

**Comment by zuoyou1314** [comment]
you can add debug fix the problem.

#ifdef DEBUG
#import <FLEX.h>
#endif

#ifdef DEBUG
    [[FLEXManager sharedManager] showExplorer];
#endif

**Comment by NSExceptional** [comment]
Can you provide and upload a simple repro case?

**Comment by sauravexodus** [comment]
## Steps to reproduce:

1. Remove the `use_frameworks!` flag from `Podfile`
2. `pod install`
3. Build your project

You will see an exception in the linking step.

**Comment by NSExceptional** [comment]
Thank you! I will look into this

**Comment by NSExceptional** [comment]
I believe this is no longer an issue as of some more recent versions of FLEX, but please let me know if the issue persists.
