### ISSUE TITLE
crash erminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: sourceNode'

### ISSUE THREAD

**Issue by codesourse** [Flipboard/FLEX#233]
erminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: sourceNode'
*** First throw call stack:
(0x237ef7ef8 0x2370c5a40 0x237e0c06c 0x2388f83e0 0x2648684c8 0x2648668b0 0x264ad36a4 0x264ad93c8 0x264ad5314 0x264ad5248 0x264ad5018 0x26509aa1c 0x264916d50 0x2648528e0 0x26485534c 0x26484dee0 0x237e865b8 0x237e86538 0x237e85e1c 0x237e80ce8 0x237e805b8 0x23a0f4584 0x2648fb558 0x102c2fb88 0x237940b94)

**Comment by NSExceptional** [comment]
This is not an issue with FLEX, that is a crash within your own app.

**Comment by codesourse** [comment]
*** Assertion failure in -[UIGestureGraphEdge initWithLabel:sourceNode:targetNode:directed:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.84.15/Source/GestureGraph/UIGestureGraphEdge.m:24
2019-01-17 20:53:12.739365+0800 WeChat[4979:527521] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: sourceNode'
*** First throw call stack:
