### ISSUE TITLE
Support for new architecture arm64e

### ISSUE THREAD

**Issue by Sopan** [Flipboard/FLEX#234]
Looks like there is a new architecture added "arm64e" on new iPhone hardware (iPhone Xs and iPhone Xs Max) because of which I am seeing an issue (undefined architecture arm64e) whenever I try building my app on these devices through Xcode 10.

The warning is
```
ignoring fie ./FLEX.framework/FLEX, missing required architecture arm64e in file FLEX.framework/FLEX (4 slices)
```

Looks like currently the framework built for following architectures
```i386 x86_64 armv7 arm64```
I used ```xcrun -sdk iphoneos lipo -info ./FLEX.framework/FLEX``` to figure it out.

Is there a plan to support this new architecture in Flex?

**Comment by NSExceptional** [comment]
I believe `arm64e` will become part of `$STANDARD_ARCHS` in a later version of Xcode. You can [manually enable it](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_1_release_notes?language=objc) if you wish. Closing this issue for now.
