### ISSUE TITLE
Allow opening a UIFont as a regular class

### ISSUE THREAD

**Issue by revolter** [Flipboard/FLEX#235]
It currently opens a quick change window that let's you update its family and size, but I would like to be able to inspect other properties of the `UIFont` class.

**Comment by NSExceptional** [comment]
If you call the method instead it should take you to the font.

**Comment by NSExceptional** [comment]
Sounds like a good idea to me. PRs welcome!

**Comment by NSExceptional** [comment]
Feature = added

**Comment by revolter** [comment]
Brilliant! Thank you ❤️
