### ISSUE TITLE
Add search table by name

### ISSUE THREAD

**Issue by revolter** [Flipboard/FLEX#236]
It would be great if a search bar would be present when opening a database so you can easily search for a table by its name.

**Comment by NSExceptional** [comment]
PRs welcome! That does sound like a neat feature.

**Comment by revolter** [comment]
Is there an existing similar implementation that could be reproduced in the database related view controller?

**Comment by NSExceptional** [comment]
Someone actually already added a search bar for tables, I guess I'll close this 😅
