### ISSUE TITLE
Crash on "views" button - [UIView setImage:]: unrecognized selector sent to instance 0x7fdeabe56010

### ISSUE THREAD

**Issue by Loward1988** [Flipboard/FLEX#237]
My iOS program will crash when I tap the button "views" of FLEX toolbar, but other buttons will be okay, who know why?  Thank u guys beforehand.
Error on console：
2018-10-16 12:17:45.934027+0800 ECAME[17738:189637] -[UIView setImage:]: unrecognized selector sent to instance 0x7fdeabe56010
2018-10-16 12:17:45.939890+0800 ECAME[17738:189637] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setImage:]: unrecognized selector sent to instance 0x7fdeabe56010'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010f88629b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010ee22735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f8a4fa4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x000000011807c163 -[UIResponder doesNotRecognizeSelector:] + 287
	4   CoreFoundation                      0x000000010f88afb6 ___forwarding___ + 1446
	5   CoreFoundation                      0x000000010f88ce88 _CF_forwarding_prep_0 + 120
	6   UIKitCore                           0x00000001180e03ba -[UISearchBar(UISearchBarStatic) _updateMagnifyingGlassView] + 564
	7   UIKitCore                           0x00000001180e04ef -[UISearchBar(UISearchBarStatic) _setupSearchField] + 249
	8   UIKitCore                           0x00000001180d24db -[UISearchBar searchField] + 42
	9   UIKitCore                           0x00000001180d302b -[UISearchBar setPlaceholder:] + 52
	10  FLEX                                0x000000010c58f5a6 -[FLEXHierarchyTableViewController viewDidLoad] + 646
	11  UIKitCore                           0x00000001183c3781 -[UIViewController loadViewIfRequired] + 1186
	12  UIKitCore                           0x00000001183c3be0 -[UIViewController view] + 27
	13  UIKitCore                           0x0000000117f8d543 -[UINavigationController preferredContentSize] + 197
	14  UIKitCore                           0x0000000117ffc7ea -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	15  UIKitCore                           0x0000000117ff8409 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 116
	16  UIKitCore                           0x0000000117ca097e _runAfterCACommitDeferredBlocks + 318
	17  UIKitCore                           0x0000000117c8f424 _cleanUpAfterCAFlushAndRunDeferredBlocks + 384
	18  UIKitCore                           0x0000000117cbe870 _afterCACommitHandler + 135
	19  CoreFoundation                      0x000000010f7e9037 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	20  CoreFoundation                      0x000000010f7e34ce __CFRunLoopDoObservers + 430
	21  CoreFoundation                      0x000000010f7e3b61 __CFRunLoopRun + 1537
	22  CoreFoundation                      0x000000010f7e3221 CFRunLoopRunSpecific + 625
	23  GraphicsServices                    0x000000011457d1dd GSEventRunModal + 62
	24  UIKitCore                           0x0000000117c95115 UIApplicationMain + 140
	25  ECAME                               0x0000000109dc7104 main + 68
	26  libdyld.dylib                       0x0000000111645551 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by NSExceptional** [comment]
Does your app customize the search bar at all?

**Comment by Loward1988** [comment]
I think the problem is that UIView point points to UIImageView object somewhere in my app. I resolve this problem through implementing the function 'setImage' of UIView, return nil in it. Then I can play FLEX normally

**Comment by Loward1988** [comment]
I think the problem is that UIView point points to UIImageView object somewhere in my app. I resolve this problem through implementing the function 'setImage' of UIView, return nil in it. Then I can play FLEX normally
