### ISSUE TITLE
Update Cocoapods version

### ISSUE THREAD

**Issue by AnthoPakPak** [Flipboard/FLEX#238]
I think you should update Cocoapods version, as the latest (2.4) is a bit outdated compared to changes made on the repo.

For now I recommend using `pod 'FLEX', :git => 'https://github.com/Flipboard/FLEX.git', :configurations => ['Debug']` to be sure to have latest changes (such as saving/restoring bar place for example).

Thanks in advance.

**Comment by NSExceptional** [comment]
I'll get to this eventually!

(If I can; it's been a while since I've used Cocoapods, do I have the authority to update the pod just by having commit access?)

**Comment by revolter** [comment]
You could simply run `pod trunk push` and see if it works.
