### ISSUE TITLE
Can't modify frame in HEAD version

### ISSUE THREAD

**Issue by revolter** [Flipboard/FLEX#244]
In the latest version, the `frame` of a `UIView` shows up as `NSRect` and you can't edit it anymore:

<img width="1047" alt="screen shot 2018-11-14 at 18 16 04" src="https://user-images.githubusercontent.com/5748627/48495780-5fa18180-e839-11e8-86cd-fee497e18ba6.png">

**Comment by NSExceptional** [comment]
Which app are you testing this in? I am able to modify frames of views on my device

**Comment by revolter** [comment]
In the app I'm working on. I'll try to reproduce it and get back to you. Are you using Xcode 10 as well?

**Comment by NSExceptional** [comment]
Yep!

How are you accessing the frame?

**Comment by revolter** [comment]
I'm selecting a view, then tap the `frame` property:

![Image](https://i.imgur.com/vjUf2oH.jpg)

**Comment by NSExceptional** [comment]
I will look into this, thanks!

**Comment by AYastrebov** [comment]
The same problem

**Comment by NSExceptional** [comment]
This has since been fixed in a more recent commit, I forgot to close this. It's after 3.0.0 but not in a release yet.

**Comment by revolter** [comment]
Yup, it works, thanks a lot!
