### ISSUE TITLE
Websockets support or similar library

### ISSUE THREAD

**Issue by Ricardo1980** [Flipboard/FLEX#246]
Hello,

I have been using this library for years in different companies, it is really useful. Thanks for that.
My current project uses websockets.
Will this library implement that?
Otherwise, do you know any other library to introspect websockets in iOS?

Thanks for suggestions.

**Comment by NSExceptional** [comment]
No plans as far as I know. PRs welcome!

**Comment by Ricardo1980** [comment]
@NSExceptional 
Thanks for reply. I understand that is a big task.
Using a network sniffer like Wireshark is a bit complex for that. 
Testing iPhone Charles right now (I see them encrypted).
Do you know any other tool that could be helpful?
Thanks a lot.

**Comment by NSExceptional** [comment]
If they are encrypted, you can try to install the Charles root certificate and trust it (instructions on their website) but you might need a jailbroken device to see the traffic even then.

Also, Charles is only for HTTP/S, not for all websockets.

**Comment by Ricardo1980** [comment]
That's what I thought, but I see web-sockets in Charles, although the content is encrypted:

![photo 03-12-2018 20 19 36](https://user-images.githubusercontent.com/738681/49400150-4eaea680-f73b-11e8-9d50-9722ab9a13ce.png)

![photo 03-12-2018 20 20 01](https://user-images.githubusercontent.com/738681/49400156-54a48780-f73b-11e8-84df-e84f57b55ed4.png)
