### ISSUE TITLE
It will crash when malloc return NULL

### ISSUE THREAD

**Issue by cocoongg** [Flipboard/FLEX#247]
In the FLEXNetworkObserver.m, line 186, the code is 
"classes = (__unsafe_unretained Class *)malloc(sizeof(Class) * numClasses);",
if allocation failed , a nil will be returned, then crash happen.

**Comment by NSExceptional** [comment]
I'll see if I can make that method failable, good catch!

**Comment by cocoongg** [comment]
> I'll see if I can make that method failable, good catch!

Thanks for your comment,
I use the code in my APP, and got two semblable crashes, one is 

> Crashed: NSOperationQueue 0x282b160c0 (QOS: UNSPECIFIED)
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x0000000110760000

and another is :

> #0 Crashed: NSOperationQueue 0x2838f1c60 (QOS: UNSPECIFIED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000020000000020 
0 | libobjc.A.dylib | class_copyMethodList 

I do not know the difference between KERN_PROTECTION_FAILURE and  KERN_INVALID_ADDRESS, 
But, I guess maybe the malloc() failed.

**Comment by shusain93** [comment]
I don't think you can get iOS to return nil on malloc as you'll get jettisoned before you fail to allocate memory

**Comment by NSExceptional** [comment]
@shusain93 Do you have a source on that? I couldn't find anything on it, but I have heard that before.

**Comment by shusain93** [comment]
I guess I was sort of correct. Try this code:

```
while (1) {
        if (malloc(80000) == 0x0) {
            usleep(500000);
            printf("GOT NIL!!\n");break;
        }
}
```

The app isn't being jettisoned but instead iOS does abort when it fails to call malloc when creating Objective-C objects. I don't know what's being created but it's some random object that iOS needs for the app. See the crash log:

```
sadfghj(281,0x1024feb80) malloc: can't allocate region
*** mach_vm_map(size=81920) failed (error code=3)
sadfghj(281,0x1024feb80) malloc: *** set a breakpoint in malloc_error_break to debug
GOT NIL!!
sadfghj(281,0x1024feb80) malloc: can't allocate region securely
sadfghj(281,0x1024feb80) malloc: *** set a breakpoint in malloc_error_break to debug
sadfghj(281,0x1024feb80) malloc: can't allocate region securely
sadfghj(281,0x1024feb80) malloc: *** set a breakpoint in malloc_error_break to debug
2019-04-17 15:32:52.941744-0600 sadfghj[281:5564] *** Terminating app due to uncaught exception 'NSMallocException', reason: '*** NSAllocateObject(): attempt to allocate object of class '__NSFastEnumerationEnumerator' failed'
*** First throw call stack:
(0x1ad51cec4 0x1ac6eda40 0x1ad52b218 0x1adea8134 0x1afd37794 0x1afd376d4 0x1afd37c48 0x1afd37a7c 0x1afd37bc4 0x1aff8cccc 0x1aff5249c 0x1da2d25fc 0x1da6ed7b8 0x1da6ed71c 0x1da144f44 0x1da722de4 0x1da722f90 0x1da733f98 0x1da6e3d78 0x1da6e9714 0x1d9f85074 0x1d9f8dcf4 0x1d9f84cf0 0x1d9f85690 0x1d9f83790 0x1d9f8343c 0x1d9f885fc 0x1d9f8955c 0x1d9f884b4 0x1d9f8d3a0 0x1da6e7c0c 0x1da2d297c 0x1aff539d4 0x1aff5e79c 0x1aff5de94 0x102304dc8 0x102308a10 0x1aff92a9c 0x1aff92728 0x1aff92d44 0x1ad4ad1f0 0x1ad4ad170 0x1ad4aca54 0x1ad4a7920 0x1ad4a71f0 0x1af720584 0x1da6eb4c0 0x10226288c 0x1acf66bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

So either way, you should never end up getting a pointer to invalid memory from malloc unless you corrupt the malloc table through double free or something like that because you'll just (apparently) crash when attempting to allocate when no memory is available. Either this is a really bad bug or very bad user error. Nasty.

**Comment by NSExceptional** [comment]
Yeah, that's what I thought.

I'll close this then, but @cocoongg if you could provide a crash log I'd be happy to verify whether FLEX is the cause of the crash or not.
