### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by geor-kasapidi** [Flipboard/FLEX#252]
Hi! Do you have plan to release new version, ex. 2.5??

**Comment by NSExceptional** [comment]
Yeah, I plan to update the pod and push a new version once I fix the System Log tab for iOS 10+. I haven't had a whole lot of time lately to get to it. Help would be appreciated!

**Comment by geor-kasapidi** [comment]
Well, i can fix this) I will make PR soon

**Comment by NSExceptional** [comment]
I've made progress on the system logging fix. Just a heads up.

**Comment by geor-kasapidi** [comment]
@NSExceptional wait for your solution, because i didn't found way how to display os_logs inside app :( maybe it's better to make some proxy logger inside FLEX to use in app instead of direct os_log api calling...

**Comment by NSExceptional** [comment]
I figured it out, I'm just cleaning it up and adding some message caching and we'll be good to go

**Comment by crazypoo** [comment]
hola!this code can show os_logs inside app,https://github.com/shixueqian/iOSLogTool.check it

**Comment by Kaspik** [comment]
afaik master is already updated and fixed, looks great - any update on the release for cocoapods then? :) Is there anything missing? Feels like it could be even called 3.0.

**Comment by NSExceptional** [comment]
I've run into some issues trying to update the pod. Since our deployment target is iOS 8, we need the iOS simulator for Cocoapods to validate it I think. And you can't download that without an old version of Xcode. And older versions of Xcode won't run on Mojave. And Mojave won't let you download old versions of macOS...

I'll keep you all updated.

**Comment by Kaspik** [comment]
I see, yeah. Honestly even tho `Xcode 10.2 supports on-device debugging for iOS 8`, I would probably drop iOS 8 as even iOS 9 will be deprecated soon (WWDC is coming). There is more benefits for all developers using iOS 9+ than trying to maintain everything for iOS 8 developers.

Also, there is always option to release 3.0 as iOS 9+ and then release 2.6 for iOS 8+ developers as last release.

Anyways it's completely up to you! :)

**Comment by NSExceptional** [comment]
I think I can manage to get it working, I just need my laptop back with my copy of Sierra on it 😂

I would need it as soon as it gets sent off to the Apple store… smh
