### ISSUE TITLE
Crash ios 12 if used wifi

### ISSUE THREAD

**Issue by SergeKZ** [Flipboard/FLEX#255]
The application crashes if you enable "Network History" and use Wifi! IOS 12

**Comment by NSExceptional** [comment]
I'm unable to reproduce this. If you installed it via cocoapods, you may be using an old version, because the pod hasn't been updated in a while, but we have fixed several bugs. Try this:

```
pod 'FLEX', :git => 'https://github.com/Flipboard/FLEX.git', :branch => 'master'
```

If you're still having issues after that, I'll reopen this and we can investigate this further
