### ISSUE TITLE
2.0.0 Not working

### ISSUE THREAD

**Issue by jolyyana** [Flipboard/FLEX#256]
it was working in older version 

But in this update the tool not showing in any app

**Comment by Kozmick** [comment]
same here

**Comment by NSExceptional** [comment]
Can you be more specific! If you can share any code I can help, but otherwise you'll have to try to debug the issue

**Comment by Kozmick** [comment]
ip6 10.2.1 using Saigon. When enabling in certain apps/springbored the UI just wont show up in any apps.

**Comment by NSExceptional** [comment]
This repo has nothing to do with jailbreaking. It has been made into various jailbreak tweaks, though.

**Comment by jolyyana** [comment]
After updating the tool does not appear in any app 


https://b.top4top.net/p_1173lw2x70.png

https://c.top4top.net/p_1173gn1p31.png

https://d.top4top.net/p_1173v75162.png

Iphone 6 S ios11.2.6

**Comment by NSExceptional** [comment]
This is not the FLEXible repo.
