### ISSUE TITLE
Not working on iPhone X

### ISSUE THREAD

**Issue by shuvo1003** [Flipboard/FLEX#257]
I download FLEXible on iOS ios 11.3.1 iPhone X. Enabled some apps but when I open nothing comes up.

**Comment by NSExceptional** [comment]
FLEXible is a jailbreak tweak that simply uses this library, this is not the place to ask for help with the tweak itself. Try [/r/jailbreak](https://www.reddit.com/r/jailbreak) or [/r/jailbreakdevelopers](https://www.reddit.com/r/jailbreakdevelopers).

Alternatively, try [FLEXing](https://github.com/NSExceptional/FLEXing/releases) which is available on BigBoss.
