### ISSUE TITLE
the action sheets cover the explorerWindow

### ISSUE THREAD

**Issue by leexiaosi** [Flipboard/FLEX#26]
The action sheets cover the explorerWindow, So I can't touch the explorerWindow.
![image](https://cloud.githubusercontent.com/assets/516562/3971767/e4e21f58-27d6-11e4-9b07-4d1fe82b80ca.png)

I think it should be 

      self.explorerWindow.windowLevel = UIWindowLevelAlert * 2;

Thanks.

**Comment by ryanolsonk** [comment]
There's a tradeoff here that I think we'll have to live with. The FLEX modals need to present alerts and action sheets, so having the FLEX window above the alert level is not an option. If you're interested in exploring alerts, you can temporarily raise the FLEX window level.
