### ISSUE TITLE
[FLEXNetworkHistoryTableViewController]SearchBar missing when searchController actived

### ISSUE THREAD

**Issue by CNHarrySun** [Flipboard/FLEX#262]
Network History ----> Search，The following phenomenon:
<img src="https://user-images.githubusercontent.com/16249166/55935368-0a419300-5c66-11e9-8108-dea959d99aed.png" width="50%" height="50%">

**Comment by CNHarrySun** [comment]
> Network History ----> Search，The following phenomenon：
> ![image](https://user-images.githubusercontent.com/16249166/55935368-0a419300-5c66-11e9-8108-dea959d99aed.png)

fix：
add code in FLEXNetworkHistoryTableViewController
self.extendedLayoutIncludesOpaqueBars = YES;

**Comment by NSExceptional** [comment]
I'm unable to reproduce this, can you provide some more information?

- Device
- iOS version
- Xcode version
- How you installed FLEX in your project

**Comment by CNHarrySun** [comment]
Device：iPhone XR
iOS version：12.2 / 12.1.3
Xcode version：Version 10.1 (10B61)
FLEX files added manually to a project

**Comment by CNHarrySun** [comment]
and FLEX added with CocoaPods

**Comment by NSExceptional** [comment]
I'm unable to reproduce this. If you installed it via cocoapods, you may be using an old version, because the pod hasn't been updated in a while, but we have fixed several bugs. Try this:

```
pod 'FLEX', :git => 'https://github.com/Flipboard/FLEX.git', :branch => 'master'
```

**Comment by CNHarrySun** [comment]
I can't duplicate it in the iPhone XR right now.
Try this：
Device：iPhone 5S
iOS version：9.3.1
Xcode version：Version 10.1 (10B61)
FLEX files added manually to a project

**Comment by NSExceptional** [comment]
Still unable to replicate it in the demo app. Can you send me a sample project? Also, can you try Xcode 10.2? 10.2 is out now
