### ISSUE TITLE
how can i configurate to let flex supported to view systerm log?

### ISSUE THREAD

**Issue by itanchao** [Flipboard/FLEX#268]
I can not see the systerm log now

**Comment by NSExceptional** [comment]
I need a little more information than that

How did you install FLEX? If you're using CocoaPods, post the relevant portion of your podfile

**Comment by itanchao** [comment]
`pod 'FLEX','2.4.0'
    `
actually the features except view logs can work it well

**Comment by NSExceptional** [comment]
Use this instead until I update the pod, 2.4.0 is very old and doesn't support logs on iOS 10+

```
pod 'FLEX', :git => 'https://github.com/Flipboard/FLEX.git'
```
