### ISSUE TITLE
Non-public API usage:

### ISSUE THREAD

**Issue by khoren93** [Flipboard/FLEX#269]
I got this mail from App Store Connect.
My app is educational, so FLEX is available in the app store version too :)

Dear Developer,

We identified one or more issues with a recent delivery for your app, "SwiftHub - Git Client". Please correct the following issues, then upload again.

Non-public API usage:

The app references non-public selectors in Frameworks/FLEX.framework/FLEX: _canPerformAction:forCell:sender:, _performAction:forCell:sender:, _tableView, allObjects:, schema

If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

**Comment by NSExceptional** [comment]
Hi,

Yes, FLEX uses many private APIs. You should not include FLEX in your release builds when you submit to the App Store, this being one of many reasons

Set up your podfile to only include it in the Debug configuration like so:

```
pod 'FLEX', :configurations => ['Debug']
```

**Comment by MatrixSenpai** [comment]
Arguably there's no reason FLEX should be in a production build. Even if it _can_ be used, it most definitely _should not_, especially if there are app secrets and runtime stuff that shouldn't be available to the end user

**Comment by NSExceptional** [comment]
Yeah I'm just gonna leave this closed on second thought. OP, feel free to submit a PR with obfuscated selectors is you need them sooner than I can get around to it.

**Comment by inonomori** [comment]
In my case, I do want to include FLEX in our TestFlight build, some of our public testers can use it to help them find bugs.

**Comment by so898** [comment]
The same as @inonomori .
We uploaded binary with FLEX to App Store for internal Testflight usage. App Store reject our binary and ask us to remove these private APIs in FLEX.
We just want our team member in other regions to join the test.
Now we can only revert FLEX to previous version for Testflight.
Please obfuscating these private APIs.
That will be a huge help to us.

**Comment by NSExceptional** [comment]
This is probably none of my business, but if you want to use something like this for team members, that's what ad-hoc builds are for. You can distribute builds to your team without going through Apple. Just a friendly FYI!

> In my case, I do want to include FLEX in our TestFlight build, some of our public testers can use it to help them find bugs.

How does FLEX enable testers, who probably aren't programmers, to find bugs? Can you give me an example? (Please excuse my ignorance, I personally use FLEX as a reverse engineering tool more than a debugger)

**Comment by inonomori** [comment]
for instance, our testers use FLEX to modify user default data to cover several different cases, or monitor network requests to check if some parameters are missing or response is incorrect. of course they still have other ways to do those like use Charles, but FLEX is more convenience.

**Comment by inonomori** [comment]
I think the problem is we use test flight more like internal test instead of public test. I agree ad-hoc builds are the solution.

**Comment by gelosi** [comment]
Can add my 5 cent: unless restricted API use is the only way to go → we'd better avoid that. Really useful to have FLEX in TestFlight builds...

**Comment by NSExceptional** [comment]
If you're using TestFlight for internal testing, there is a group of users you can use for internal testing which bypasses app review. It's called "App Store Connect Users." You should use this if you want to allow employees to debug the app with FLEX.

(Another option is AdHoc distribution, but that's a little more involved, which is why TestFlight is a thing of course)

That said, I welcome any PRs which _elegantly_ obfuscate private API usage.

**Comment by MatrixSenpai** [comment]
I disagree with @gelosi. These are _private_/_restricted_ APIs, and for a reason. FLEX is designed to access part of iOS that is debug-only. It's bad style to try and obfuscate private APIs for TestFlight builds _specifically because_ these builds are designed to be _like release_. Therefore they should behave as such. If you're using TestFlight builds to distribute your app to your organization, you're doing it wrong. That's what AdHoc is for. My recommendation is to close this.

**Comment by gelosi** [comment]
@MatrixSenpai totally agree on the point regarding TestFlight test distribution. My point: well, distributing through adHoc is pita. Thus, I have a separate account for TestFlight Test Only builds. Works like charm. Infecting production is impossible this way. Everybody's happy.
I don't mind to think nice obfuscation (I don't believe it exists though, will be somehow alien...) 
What I can imagine is having different build targets: full and TF friendly. FLEX, FLEX-Limited → some features are missing, no restricted borders crossed, no hacks and obfuscations...
Pita shifts to the support line indeed...  – what do you think on this approach?
//cc @NSExceptional

**Comment by luowei** [comment]
**I have remove Private APIs in Flex , but still tell me., how could I resolve the problem except for remove the Flex library.**  
```
Your app uses or references the following non-public APIs:

Symbolication.framework
ContactsFoundation.framework
Celestial.framework
LoggingSupport.framework
WebKitLegac.framework

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change. 
```

**Comment by NSExceptional** [comment]
I think I'm actually going to update the license to say that you're not allowed to use FLEX at all in consumer-facing applications.

@luowei do not remove just the private API usages. **DO NOT** include FLEX in builds submitted to the App Store **at all**

**Comment by MatrixSenpai** [comment]
I agree with this move. I don't think there's any real reason you should be using FLEX in production builds, as I stated before. They're good for debugging, but ultimately someone will discover that you've used them in your prod build, and that could have some pretty disastrous results imo

**Comment by luowei** [comment]
Yes, I'm also agree that would be dangerous for apple developer account, and very unsafe for consumers. I have remove FLEX at all in consumer-facing applications.
