### ISSUE TITLE
PAC crash on A12 devices

### ISSUE THREAD

**Issue by opa334** [Flipboard/FLEX#271]
Some features such as "Heap Objects" and "Live Instances" crash on A12 devices. The [crash log](https://pastebin.com/HTg47Tev) mentions a pointer authentication failure.

This gist should be useful: https://gist.github.com/summertriangle-dev/6b0449ce561f756ac82a4bc3de7af30a

**Comment by NSExceptional** [comment]
You're looking for the FLEXing repo, not FLEX.

Also, that crash log is not symbolicated.

**Comment by opa334** [comment]
Alright, wasn't exactly sure where to submit this, will move it there.

The crash log is not symbolicated because there is currently no way to symbolicate crash logs on A12 devices, but it should be easily reproducable.

**Comment by NSExceptional** [comment]
If you plug your device into Xcode and open the devices pane you should be able to view symbolicated crash logs from there.
