### ISSUE TITLE
Som method names in your source code match the private Apple APIs listed above.

### ISSUE THREAD

**Issue by zhipengbird** [Flipboard/FLEX#274]
when i archived my app to testflight. received some warnings.
`Non-public API usage - The app references non-public selectors in StarMaker: _canPerformAction:forCell:sender:, _performAction:forCell:sender:, allObjects:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions.`
please fixed.

**Comment by NSExceptional** [comment]
You shouldn't include FLEX in your app when you submit it to the app store. Only for testing. Add this to your podfile:

```ruby
pod 'FLEX', :configurations => ['Debug']
```

Then `#if DEBUG` in your code around where you activate FLEX. Make sure the DEBUG macro is set in build settings.

https://stackoverflow.com/a/9063469
