### ISSUE TITLE
Logs not working on ios 11

### ISSUE THREAD

**Issue by marquisd** [Flipboard/FLEX#278]
Hi.  Logs are not working for us. 

iOS 11

On a device, there is nothing and on the simulator, I get the two following logs:

```
2019-05-16 13:10:57.700: assertion failed: 18F132 16B91: libxpc.dylib + 79599 [F7D4B188-D5C2-3E5E-BB76-BC7C6A36166]: 0x7d

2019-05-16 13:10:57.700: (null)
```

Is this something common and there is a known fix? or let me know if you need additional information.

**Comment by NSExceptional** [comment]
How did you install FLEX into your project?

**Comment by marquisd** [comment]
holy man.  That was a quick response.  I didn't even have time to close the page.  haha.

Cocoapods.

here's our line in podfile:
```
pod 'FLEX', '~> 2.0', :configurations => ['debug dev', 'debug prod', 'debug qa']
```

**Comment by NSExceptional** [comment]
Email notifications help haha

Remove the `'~> 2.0',` part and run `pod install`, this should update it to `3.0.0`. After that, does it work?

**Comment by marquisd** [comment]
Yup.  That did it.  Thanks.
