### ISSUE TITLE
Request for information on getting started.

### ISSUE THREAD

**Issue by Joj0Z** [Flipboard/FLEX#279]
I am new and was considering contributing. That said I was wondering if there was anything I need to know to get started. The contributing.md just says to make a pull request. I was wondering if there are any naming or comment conventions that are used as well as if there are any standards that I should observe while I am working on the project? Also, any other information a new contributor should know would be great.

**Comment by NSExceptional** [comment]
Hey! Thanks for taking an interest in contributing.

There's no official set of conventions as far as I can tell, but if you follow the code style set forth in the project already, you should be fine. Be mindful of whitespace though. Here's a quick example of some do's and don'ts:

```objc
// yes
- (void)foo:(id)f bar:(void *)bar
{
    if (condition) {
        ...
    }
}

// nooo
// yes
-(void)foo: (id)f bar:(void*) bar{
    if(condition){
        ...
    }
}
```

Let me know if you have any other questions!
