### ISSUE TITLE
Heap objects can not find UIViewController instance

### ISSUE THREAD

**Issue by ZuhanLin** [Flipboard/FLEX#283]
Hi, Big Lao. i can not find UIViewController inherit instances when I use FLEX to watch live instances,  issues version is 3.0.0  while it is well in version 2.4.0
![BA3CFD89-B22A-4089-998B-A75C5FAF2045](https://user-images.githubusercontent.com/5183529/58863757-03735180-86e6-11e9-8e99-dfc12198f556.png)

**Comment by NSExceptional** [comment]
Closing as a probable duplicate of #248
