### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 60

### ISSUE THREAD

**Issue by base0225** [Flipboard/FLEX#292]
hi,I clone meet some problem:
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (66/66), done.
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly

**Comment by NSExceptional** [comment]
This is not an issue with the repo; I would contact GitHub or ask StackOverflow.
