### ISSUE TITLE
Network History search bar appearing over nav bar

### ISSUE THREAD

**Issue by WolfAloneLJ** [Flipboard/FLEX#295]

**Comment by BetaTiger** [comment]
The same issues for me.

**Comment by NSExceptional** [comment]
?

**Comment by BetaTiger** [comment]
![1563809222555](https://user-images.githubusercontent.com/11539098/61644941-3e523880-acd8-11e9-951e-880d7a20aaa9.jpg)
As the picture show,The navigation cover the tableview's top section. That leads to we can not touch the first tableview's first row.

**Comment by NSExceptional** [comment]
- Which version of FLEX are you using?
- Are you doing anything custom with your navigation bars?
- Is the project this is in open source?

**Comment by NSExceptional** [comment]
We've completely rewritten this part of the codebase now, so I'm gonna close this. You won't see this change until I push 3.1.0 to Cocoapods, though.
