### ISSUE TITLE
Missing FLEXGlobalsRowFileBrowser globalsRow

### ISSUE THREAD

**Issue by iunion** [Flipboard/FLEX#300]
Missing FLEXGlobalsRowFileBrowser item in FLEX menu - "File Browser"

add 
[self globalsEntryForRow:FLEXGlobalsRowFileBrowser],
in
+ (NSArray<NSArray<FLEXGlobalsTableViewControllerEntry *> *> *)defaultGlobalSections

**Comment by NSExceptional** [comment]
I have this fixed on another branch. In a couple of days I'll have it all merged into master, keep an eye out. I'll close this issue then.
