### ISSUE TITLE
Force fullscreen presentation for flex tool modals

### ISSUE THREAD

**Issue by ryanolsonk** [Flipboard/FLEX#313]
The new iOS 13 modal card style is awkward when presented from the flex window. Let's keep the presentation fullscreen which is the default for previous iOS versions.

**Comment by NSExceptional** [comment]
What do you find awkward about it?

I think it's convenient to be able to dismiss FLEX without needing to go to the top of the navigation stack, and without needing to use a "Done" button on every single screen. I've also seen a few requests for being able to dismiss and reveal FLEX without "losing your place" so to speak; I think the card style could fit into this nicely. I was considering mimicking it on earlier versions of iOS even, but I would love to hear other ideas

**Comment by ryanolsonk** [comment]
There's a pushback/dim animation of the clear FLEXExplorerViewController which looks pretty off to me, but I'm fine to keep it for the utility.

**Comment by ryanolsonk** [comment]
Example of the animation:
https://gfycat.com/afraidrecentchimneyswift
