### ISSUE TITLE
Update screenshots in README

### ISSUE THREAD

**Issue by matrush** [Flipboard/FLEX#320]
The screenshots and GIFs are pretty outdated since those were added several years ago. We should see if we can update them to make the project feels more modern.

**Comment by NSExceptional** [comment]
I recorded some videos, but I'm having trouble finding a site that will convert them to acceptable-quality GIFs. Even _Gfycat_ of all sites won't let you download a GIF anymore. Any ideas?

cc @ryanolsonk

**Comment by ryanolsonk** [comment]
I think I used https://www.cockos.com/licecap/ originally

**Comment by NSExceptional** [comment]
Ah, crap. I'll use that too if it comes to it. I have all 9 replacement videos already recorded though so I'm gonna see if I can get those to GIFs somehow first haha

**Comment by ryanolsonk** [comment]
Could use ffmpeg in that case

https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/

**Comment by NSExceptional** [comment]
Huh, that did the trick pretty smoothly! I was afraid the default settings would produce really large files or something, but they're not much larger than the videos themselves.

```bash
for file in `ls`; do
    file=`basename $file .mov`
    ffmpeg -i $file.mov -f gif $file.gif
done
```

**Comment by NSExceptional** [comment]
e862b81 closes this

**Comment by matrush** [comment]
Thank you ❤️
