### ISSUE TITLE
Some buttons disappear

### ISSUE THREAD

**Issue by mauromdq** [Flipboard/FLEX#327]
Hi,
I use Flex 3.0.0 en my iPhone 6s and works fine, but when I enter in some screens the "Settings" topBar's button disappear. (tapping on "settings" button and going back)
Something similar happened to someone??
Thanks in advance!

![flex](https://user-images.githubusercontent.com/6059914/64367653-f7ea3c00-cfee-11e9-9c62-067cef5c59f8.jpg)

**Comment by NSExceptional** [comment]
I'm unable to reproduce it at all on iOS 13 (it looks like you're on 13,  is that right?). Is the button just the wrong color or is it actually gone?

**Comment by mauromdq** [comment]
Yes, I'm on 13, but it also happens on my other devices with ios 12.
The button is still there, in fact, the tap action works well, but the button's text doesn't look.
Thanks!

**Comment by NSExceptional** [comment]
Sounds like your own app is doing something fishy, unless you can reproduce it in the demo app.

Are you doing anything funky with `UIAppearance` stuff or swizzling anything?
