### ISSUE TITLE
Deprecated UIViewWeb warning from App Store Connect

### ISSUE THREAD

**Issue by bull-xu** [Flipboard/FLEX#328]
When a build submitted to App Store Connect, a warning email received:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

`FLEXWebViewController` is still using the UIWebView - is it possible to update to UKWebView?

**Comment by NSExceptional** [comment]
The latest pod version still uses it but the `master` branch has migrated to WKWebView. You can tell your podfile to use the master branch.

**Comment by NSExceptional** [comment]
Hey @bull-xu, I’ve pushed a cocoapods release with these changes, so you should be able to go back to using `pod 'FLEX'` again
