### ISSUE TITLE
Unable to do method calls or edit fields

### ISSUE THREAD

**Issue by DGh0st** [Flipboard/FLEX#329]
The latest commit (well since [07f0b07](https://github.com/Flipboard/FLEX/commit/07f0b07a91d89428dbe9c29840c9ac7ea9f6726a) which fixes a crash issue) is unable to do method calls via the explorer, everything is no-oping. All the properties/fields are defaulting to 0 and trying to set them does nothing (setting the frame for instance).

![image](https://user-images.githubusercontent.com/13194700/64924508-d3d6e980-d7aa-11e9-9376-d0be2ee4e6fa.png)

In that commit, not calling `[invocation invoke];` seems to be culprit for the default values but not sure about method calls being no-oped.

**Comment by DGh0st** [comment]
I tried checking out the latest commit with [07f0b07](https://github.com/Flipboard/FLEX/commit/07f0b07a91d89428dbe9c29840c9ac7ea9f6726a) reverted and that seems to fix this issue completely. This means that if statement is the cause of the method calls not working too.

**Comment by NSExceptional** [comment]
Nah, it's because I removed that `-invoke` call like you said. Originally I meant to just remove the comments above it I think.

The if statement I added is to avoid calling methods we can't get the return values of anyway.

Thanks for catching this! Dunno how I overlooked this...

**Comment by DGh0st** [comment]
Pretty sure the methodReturnLength is 0 for methods that have return type of void which is why I wasn’t able to set the frame even after re-adding invoke.

**Comment by NSExceptional** [comment]
Wow, I goofed again. I'm gonna force-push all three of these fixes into one commit for cleanliness, so you'll have to do a force-pull. Thanks again!
