### ISSUE TITLE
Installing flex using carthage

### ISSUE THREAD

**Issue by kennyzi** [Flipboard/FLEX#336]
i am still struggling to install flex using carthage if i want to exclude it from two different build. can someone help with with a detail tutorial or a maybe a video?

**Comment by NSExceptional** [comment]
Unless this problem is specific to FLEX, this is not a place for general programming help. Try [Reddit](https://reddit.com/r/iOSProgramming) or the [Carthage repo itself](https://github.com/Carthage/Carthage/issues)
