### ISSUE TITLE
Not Showing Explorer

### ISSUE THREAD

**Issue by yusufozgul** [Flipboard/FLEX#340]
Not Showing Explorer on iOS 13 device and Simulator. I using call `FLEXManager.shared().showExplorer()` in ViewController.

**Comment by NSExceptional** [comment]
Can you provide some more details? How did you install FLEX, which version of FLEX are you using, etc

**Comment by yusufozgul** [comment]
I create empty project and install FLEX 3.0 using CocoaPods. Importing FLEX in ViewController, tappef button will execute this code.
`FLEXManager.shared().showExplorer()` but FLEX Explorer not showing. I found a repo using flex in the project and downloaded it.  works with the same code.  I think I'm doing something missing.

**Comment by bdotdub** [comment]
@yusufozgul I had to pull from master to incorporate #304 

```ruby
pod 'FLEX', :configurations => ['Debug'], :git => "https://github.com/Flipboard/FLEX.git", :branch => 'master'
```

iOS13 deprecated `keyWindow` and  #304 fixes it

**Comment by NSExceptional** [comment]
Update your pod, I just pushed `3.1.0` with iOS 13 support. Let me know here if you are still having issues.
