### ISSUE TITLE
FLEXNetworkObserver not observe resume method

### ISSUE THREAD

**Issue by codychen123** [Flipboard/FLEX#341]
I have two projects using FLEX, but FLEX doesn't observe the `-resume` method in one of the projects.

In `+injectIntoNSURLSessionTaskResume`, the `class` used here is `__NSCFURLSessionTask`:

<image width=70% height=70% src=https://user-images.githubusercontent.com/17957287/68074245-f7460a00-fdd3-11e9-8973-515e8662a790.png>

But I find that the class AFNetworking ends up using here is `__NSCFLocalDataTask`:

<image width=70% height=70% src=https://user-images.githubusercontent.com/17957287/68074289-6b80ad80-fdd4-11e9-832e-89883ccb52b3.png>

I think `FLEXNetworkObserver` doesn't observe the `-resume` method here because it didn't swizzle the right one. When I add this code, it works:

<image width=70% height=70% src=https://user-images.githubusercontent.com/17957287/68074325-ba2e4780-fdd4-11e9-8eac-28463ba721f8.png>

The strange thing is, the other project works without any changes.

**Comment by NSExceptional** [comment]
Looks like I have some work to do. Can you upload this project or another project demonstrating the issue?

**Comment by NSExceptional** [comment]
@codychen123 Hello? I need your help, I don't have a project which demonstrates the issue

**Comment by NSExceptional** [comment]
Fixed in 4.0, see #350
