### ISSUE TITLE
Flex CocoaPods not working on target IOS13 simulator

### ISSUE THREAD

**Issue by Ali72** [Flipboard/FLEX#349]
I used Flex on my previous project only with add pod in my project but after last ios update that's not work anymore and not show flex toolbar when I click 'f' button.

**Comment by bdotdub** [comment]
@Ali72 I think this is the same issue as #340

**Comment by NSExceptional** [comment]
Update your pod, I just pushed `3.1.0` with iOS 13 support. Let me know here if you are still having issues.
