### ISSUE TITLE
Add error logging

### ISSUE THREAD

**Issue by arn8tas** [Flipboard/FLEX#358]
It would be great if FLEX would have ability to record non fatal errors.

**Comment by NSExceptional** [comment]
Can you elaborate? Are you referring to thrown but caught exceptions?

**Comment by arn8tas** [comment]
I'm referring to any error that conforms to `Error` protocol. In some cases it would be great to track some third party SDK's or internal errors that can be listed in FLEX explorer. Something similar like Crashlytics/Firebase non fatals.

**Comment by NSExceptional** [comment]
FLEX is entirely Objc only for compatability with Objc projects, I'm not sure how we could do that unfortunately

**Comment by arn8tas** [comment]
It’s just a feature request that I think would be helpful. Language is not a problem here, ‘NSError’ would do the job

**Comment by NSExceptional** [comment]
Not all Errors are NSErrors though. However if you're focused more on the errors coming out of Foundation or UIKit, those will all be NSErrors.

I'll see what I can do :)

**Comment by arn8tas** [comment]
Yes, I understand, but it's not a big deal to convert one type to another, in most cases only error code and description matters :)

**Comment by alexito4** [comment]
I think this depends on if you're thinking this to be fully automatic (like the network reporting) or with some integration. 
If we go for needing some integration, a "reporter" that could be added to any of the existing logging solutions could do the job.

**Comment by arn8tas** [comment]
@alexito4 I'm thinking about manual recording :)

**Comment by NSExceptional** [comment]
I've done some thinking. This seems like a pretty niche use case to me. Most developers only care about their own `NSErrors` and will log or display them accordingly, and I think that's what you should do here. You should be able to identify all of your own NSErrors in your project and add a print statement to them or something like that, or add your own singleton class to capture the errors and add them to your own custom section in FLEX. (See the example project for how to add your own screen to FLEX)
