### ISSUE TITLE
Is there way to learn button method name ?

### ISSUE THREAD

**Issue by serhatsezer** [Flipboard/FLEX#36]
Hi all! I'm using FLEX over the last two weeks and like it. But i run into a bit missing feature. I created UIButton manually after that I added "addTarget:action:forControlEvents" method. Here we go. I wanted to see which method called specific UIButton object but i didn't see anything about UIButton target - action. In brief, is there way to see which method  called when I tapped to UIButton?

**Comment by ryanolsonk** [comment]
There is actually an existing way to find the target/action pairs for a given `UIButton` (or any `UIControl` subclass). In the object inspector modal for your UIButton, type "target" into the search field and make sure the "Include Inheritance" segment is selected. You should see an ivar called `_targetActions` which is a mutable array. 

![screenshot 2015-01-19 14 59 47](https://cloud.githubusercontent.com/assets/1422245/5810622/601ac28e-9ffe-11e4-85e3-6f5926f9db02.png)


Tap into the ivar, and then select one of the `UIControlTargetAction` objects in the array. In that object, there is an `_action` ivar and a `_target` ivar. These will have the information you are looking for. I've improved the description for SEL properties and ivars on the top of master (53a95845f4300238653756ac86272d4bafb35bb5). You'll need to update FLEX to that commit to get a readable name for the SEL.

![screenshot 2015-01-19 15 00 07](https://cloud.githubusercontent.com/assets/1422245/5810650/c481db5e-9ffe-11e4-8c3f-51542dd7d99d.png)

Hope this helps!

**Comment by frakman1** [comment]
Thank you for explaining how to get to the "buttonClicked" method. Now, how do I call it? Normally, there is a button in the top right hand corner with the name "Call" that I can tap. How can I accomplish that on the "buttonClicked" method using the FLEX tool/menu?
