### ISSUE TITLE
The file list can be scrolled under the navigation bar area

### ISSUE THREAD

**Issue by matrush** [Flipboard/FLEX#361]
<img width=30% height=30% src=https://user-images.githubusercontent.com/627231/70358108-73959800-182d-11ea-886d-bb3170f990e1.png>

This is happening without the new card style and super broken.

**Comment by NSExceptional** [comment]
I think I fixed this in fe36b59b, are you using `3.0.1`? Can you try using `master`?

**Comment by matrush** [comment]
Cool let me try bump my version. :)

**Comment by NSExceptional** [comment]
Fixed?
