### ISSUE TITLE
window等级问题

### ISSUE THREAD

**Issue by xuXiaoDan** [Flipboard/FLEX#364]
当项目中window有多个时flex的页面显示不出来，导致flex无法使用，原因是 FLEXExplorerViewController 中UIApplication.sharedApplication.windows[1] 找到的window可能不是UITextEffectsWindow,使用遍历去查找UITextEffectsWindow，  将 
UIApplication.sharedApplication.windows[1].windowLevel = self.view.window.windowLevel + 1;
        替换为
        for (UIWindow *window in UIApplication.sharedApplication.windows) {
            if ([window isKindOfClass:NSClassFromString(@"UITextEffectsWindow")]) {
               window.windowLevel = self.view.window.windowLevel + 1;
            }
        }

---

When there are multiple windows in the project, the flex page cannot be displayed, resulting in the failure of flex. The reason is that the window found in `UIApplication.sharedApplication.windows[1]` in `FLEXExplorerViewController` may not be `UITextEffectsWindow`. Use traversal to find `UITextEffectsWindow`, and `UIApplication.sharedApplication.windows[1].windowLevel = self.view.window.windowLevel + 1;` replaced by

```objc
for (UIWindow * window in UIApplication.sharedApplication.windows) {
    if ([window isKindOfClass: NSClassFromString (@ "UITextEffectsWindow")]) {
        window. windowLevel = self.view.window.windowLevel + 1;
    }
}

**Comment by NSExceptional** [comment]
This was fixed in a later commit but I have not published a formal update yet, I'm sorry.

If you can use the `master` branch, it is fixed there! I will publish an update tomorrow, though.
