### ISSUE TITLE
beg for the answer of the code injection exercise!

### ISSUE THREAD

**Issue by bellchen** [Flipboard/FLEX#37]
The code injection is left as an exercise for the reader. 哭

**Comment by ryanolsonk** [comment]
Please see the answer to #4

**Comment by dtrukr** [comment]
Here is a ready to use library for injecting FLEX into 3rd party apps:
https://github.com/dtrukr/FLEX_injected
![settings2](https://cloud.githubusercontent.com/assets/658322/6093881/30357f4a-af13-11e4-903f-08d0f9bd82d4.png)
