### ISSUE TITLE
Is it possible to add a feature that allows to select only a part of "Description"?

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#375]
It can happen that the user is interested to copy only a part of "Description", specially when the description of the object is very long. It might be useful to allow to select the text partially.

![photo_2020-02-02_13-43-05](https://user-images.githubusercontent.com/60160187/73608534-a4434500-45c4-11ea-8ed7-23cc64e955e4.jpg)

**Comment by NSExceptional** [comment]
Unfortunately, with the way 4.0 is heading to architect the explorer screen, this would be too complex. You'll have to do what I do and just open Messages, paste it, and cut the text you do want :P Sorry!

(Also, if you're about to try 4.0, you'll notice the copy buttons are currently broken, just FYI)
