### ISSUE TITLE
Cell is wrongly tinted in the table view

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#376]
When viewing info of a color, and navigating into the table view, cells are tinted of that color.

![IMG_0252](https://user-images.githubusercontent.com/60160187/73608637-c8ebec80-45c5-11ea-9858-cc256930c295.PNG)
 A fix might be to associate a different reuseIdentifier to the cell contained in the section "1".

**Comment by NSExceptional** [comment]
This is fixed in my 4.0 branch, thank you though!
