### ISSUE TITLE
Add a Copy object button

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#377]
I got an idea. When viewing the details of an object, there should be a _Copy_ button:

![image](https://user-images.githubusercontent.com/60160187/73702444-1dd65280-46ed-11ea-90ab-5b06139349a6.jpg)

The _Copy_ button copies the object (so a check of the signature should be done before adding the _Copy_ button), and it should be possible to _Paste_ that copied object as argument of a method.

Maybe it should be possible to copy more objects, so we can paste all them in a method that has more than 1 argument.

**Comment by NSExceptional** [comment]
Long press on the description cell ;)

**Comment by Ram4096** [comment]
@NSExceptional I totally forgot that! 🤦‍♂️ Good to know. However it would be nice to copy more than one object at once, to keep track of copied addresses directly in the app so we can easily paste multiple addresses :)

**Comment by NSExceptional** [comment]
I agree! I'm going to add a "bookmark" feature at some point so you can save objects for later use in method calls
