### ISSUE TITLE
[Request] ability to post a user-specified NSNotification in the current process

### ISSUE THREAD

**Issue by captinc** [Flipboard/FLEX#382]
I’m thinking maybe add a row in the FLEX home menu that would show a UIAlertController with a text-input field. You type in the name of the notification there and then FLEX would post it

Bonus points: optionally post it as an NSDistributedNotification

**Comment by NSExceptional** [comment]
You can already do this, just go to the NSNotificationCenter class and call the appropriate methods ;)

Would you like me to add `defaultCenter` to the "misc" section to make that easier?

**Comment by captinc** [comment]
Yeah adding that would be great! Thanks
