### ISSUE TITLE
FLEX crashes after tapping App Delegate in Instagram

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#385]
The crash happens on the latest Instagram app available on the App Store.
Toggle FLEX to show the explorer, go to _App Shortcuts_ and tap App delegate.
Unfortunately Cr4shed doesn't generate a useful crash log.

**Comment by NSExceptional** [comment]
Is this still crashing with the version you have?

**Comment by Ram4096** [comment]
using [this](https://github.com/Flipboard/FLEX/issues/384#issuecomment-589384122), Instagram still crashes after tapping App Delegate.

**Comment by NSExceptional** [comment]
Do you know how to debug App Store apps with lldb over Wi-Fi?

**Comment by Ram4096** [comment]
@NSExceptional unfortunately no, and I have no idea if it is possible on Windows (I haven't MacOS).
This message helped me to understand that you aren't experiencing this issue, so I tried to disable all tweaks that are injected in Instagram. I've discovered that FLEX crashes, after tapping App Delegate, when the tweak Rocket for Instagram is installed.
Probably there is something that Rocket does with App Delegate, that it might not be the purpose of FLEX to fix.

**Comment by NSExceptional** [comment]
As long it really is isn't FLEX itself crashing, there is something I still need to fix. FLEX should never crash. But if FLEX is calling some method Rocket hooks and Rocket is crashing it, there's nothing I can do.

If you can manage to get a crash log somehow that would be perfect! You can also install lldb from Cydia and try to debug it on your device
