### ISSUE TITLE
Undefined symbol for  Architecture arm64

### ISSUE THREAD

**Issue by yonalosi** [Flipboard/FLEX#391]
### Using CocoPoads to build the archive throws:

❌  Undefined symbols for architecture arm64

> Symbol: _OBJC_CLASS_$_FLEXManager
> Referenced from: objc-class-ref in ListDetailParseSupport.o

❌  ld: symbol(s) not found for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Last lines of the Xcode's build log:
      objc-class-ref in SettingsViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

**Comment by NSExceptional** [comment]
What are the contents of your podfile?

**Comment by yonalosi** [comment]
I mean just create the archive for QA distribution, 
building the project and running in devices is working fine

This is my pod file:
```
platform :ios, '11.0'
inhibit_all_warnings!

target 'myApp' do
    
    pod 'FLEX', :configurations => ['Debug'], :modular_headers => true
    pod 'UrbanAirship-iOS-SDK', '10.1.0', :modular_headers => false
    pod 'Fabric', '~> 1.10.2', :modular_headers => true
    pod 'Crashlytics', '~> 3.14.0', :modular_headers => true
    pod 'Firebase/Analytics'
    pod 'Slyce-iOS-SDK', '5.13.2', :modular_headers => true
    pod 'SDWebImage', '4.2.2', :modular_headers => true
    pod 'Firebase/Core', '5.3.0', :modular_headers => true
    pod 'EmbraceIO', '4.1.5', :modular_headers => true
    pod 'FirebaseRemoteConfig', '3.0.0', :modular_headers => true
    pod 'Qualtrics', '1.13', :modular_headers => true
    pod 'TrustDefender', '5.4', :modular_headers => false
    pod 'ACPTarget', '~> 2.1', :modular_headers => true
    pod 'ACPAudience', '~> 2.0', :modular_headers => true
    pod 'ACPAnalytics', '~> 2.0', :modular_headers => true
    pod 'AppsFlyerAdobeExtension', '~> 1.0.11', :modular_headers => true
    pod 'ACPCore', '~> 2.0', :modular_headers => true
    pod 'ACPUserProfile', '~> 2.0', :modular_headers => true
end

```

**Comment by NSExceptional** [comment]
As I suspected, the offending line:

> pod 'FLEX', :configurations => ['Debug']

You're trying to use `FLEXManager` outside of an `#if DEBUG` group. Surround it with `#if DEBUG` and the error will go away. I'm guessing you don't want FLEX in your QA builds.

**Comment by yonalosi** [comment]
> As I suspected, the offending line:
> 
> > pod 'FLEX', :configurations => ['Debug']
> 
> You're trying to use `FLEXManager` outside of an `#if DEBUG` group. Surround it with `#if DEBUG` and the error will go away. I'm guessing you don't want FLEX in your QA builds.

Actually I want it in my QA builds not in my appStore Build

**Comment by NSExceptional** [comment]
Then archive your QA builds for "debug" instead of "release"

You still need to surround all usages of `FLEXManager with `#if DEBUG` though, or you will get the same error for App Store builds

**Comment by fmxfmx** [comment]
> ### Using CocoPoads to build the archive throws:
> ❌ Undefined symbols for architecture arm64
> 
> > Symbol: _OBJC_CLASS_$_FLEXManager
> > Referenced from: objc-class-ref in ListDetailParseSupport.o
> 
> ❌ ld: symbol(s) not found for architecture arm64
> 
> ❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> Last lines of the Xcode's build log:
> objc-class-ref in SettingsViewController.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ** ARCHIVE FAILED **

How did you solve it, I ran into the same problem

**Comment by NSExceptional** [comment]
Please see the "usage" section of the readme
