### ISSUE TITLE
4.0 prevents logs from showing up in Console.app

### ISSUE THREAD

**Issue by opa334** [Flipboard/FLEX#397]
Any NSLog that's called by my tweak (inside Safari) no longer shows up in Console.app since updating to libFLEX to 4.0.

After disabling the FLEX(all) dylib for Safari inside Choicy, it works fine again.

I'm compiling my tweak with a 13.0 sdk using theos-next.

**Comment by NSExceptional** [comment]
This is a sad side effect of how we got logs to show back up in FLEX. You can see them in the System Logs screen. If you need to see your log messages in Console.app, disable FLEX, or use os_log directly in your tweaks instead of NSLog.

**Comment by mlyxshi** [comment]
![A3EF422B-8B6B-4A2D-8413-9C6D84C31616](https://user-images.githubusercontent.com/16594754/77771602-d97a8980-7081-11ea-988b-64380f50bdec.jpeg)

>This is a sad side effect of how we got logs to show back up in FLEX. You can see them in the System Logs screen

Every app always show loading, no actual output here

**Comment by NSExceptional** [comment]
@mlyxshi iOS version and FLEX loader and version?

**Comment by onewayticket255** [comment]
> @mlyxshi iOS version and FLEX loader and version?

[*] unc0ver Version: 4.3.1
[*] Machine Name: iPhone11,6
[*] Model Name: D331pAP
[*] Kernel Version: Darwin Kernel Version 19.2.0: Mon Nov  4 17:46:11 PST 2019; root:xnu-6153.60.66~39/RELEASE_ARM64_T8020
[*] Kernel Page Size: 0x4000
[*] System Version: iOS 13.3 (Stable) (Build: 17C54)

libFlEX  4.0.0
FLEXing 1.2.0

**Comment by mlyxshi** [comment]
@NSExceptional 
unc0ver Version: 4.3.1
Machine Name: iPhone11,6
Model Name: D331pAP
Kernel Version: Darwin Kernel Version 19.2.0: Mon Nov 4 17:46:11 PST 2019; root:xnu-6153.60.66~39/RELEASE_ARM64_T8020
Kernel Page Size: 0x4000
System Version: iOS 13.3 (Stable) (Build: 17C54)

libFlEX 4.0.0
FLEXing 1.2.0
