### ISSUE TITLE
About "The code injection is left as an exercise for the reader."

### ISSUE THREAD

**Issue by itouch2** [Flipboard/FLEX#4]
I'd really like to "learning from other apps". I know that first I have to jailbreak my iPhone, but I have no idea how to inject FLEX to it. Could you give me some tips or just a hint? I will  appreciate it very much.

**Comment by dtrukr** [comment]
Here is a ready to use library for injecting FLEX into 3rd party apps:
https://github.com/dtrukr/FLEX_injected
![settings2](https://cloud.githubusercontent.com/assets/658322/6093877/1eee6bc0-af13-11e4-9365-35abf5cb5996.png)

**Comment by jkyin** [comment]
:+1:
