### ISSUE TITLE
FLEX crashes whenever I hit the "done" key when inspecting a view

### ISSUE THREAD

**Issue by kef95** [Flipboard/FLEX#400]
The error `-[FLEXExplorerViewController resignKeyAndDismissViewControllerAnimated:completion:]: unrecognized selector` gets thrown and crashes whatever process FLEX is currently loaded into

Device: iPhone 5S running iOS 12.4.

**Comment by NSExceptional** [comment]
Can you give me a crash log?

**Comment by kef95** [comment]
There's no crash log unfortunately. I should've mentioned I'm running it on a jailbroken device with FLEXall, and the apps just freeze and don't crash. I have to close them manually, and in the case of springboard I have to respring via ssh or reboot my phone.

**Comment by NSExceptional** [comment]
It is a bug in FLEXAll, after looking at it's source code. I got rid of that method. Open an issue on the FLEXAll repo.

**Comment by kef95** [comment]
Will do. Thanks a lot.
