### ISSUE TITLE
Can't find NSTimer+Blocks.h in FLEXKeyPathSearchController

### ISSUE THREAD

**Issue by mvictor27** [Flipboard/FLEX#401]
Installing version 4.0 from Cocoapods, we get error "NSTimer+Blocks.h file not found"

**Comment by NSExceptional** [comment]
Neither of those are public headers. I don't have any errors when I install FLEX into a new project… are you trying to use the key path search controller?

If not, can you upload an example project which demonstrates the error?

**Comment by mvictor27** [comment]
Yes, issue is that we have the same class name in other Pod file. :(

**Comment by NSExceptional** [comment]
Which class name? Or did you mean filename? And why did you close the issue?

**Comment by mvictor27** [comment]
We have NSTimer+Blocks same file name  in other pod.

**Comment by NSExceptional** [comment]
I will fix this in 4.1

**Comment by NSExceptional** [comment]
Fixed in 4.1.0
