### ISSUE TITLE
Version 4.0.0 prevents NSLog from showing up in the Console app on mac

### ISSUE THREAD

**Issue by JamieBerghmans** [Flipboard/FLEX#402]
Using the latest version (4.0.0), NSLog no longer shows up in the Console app on Mac. Disabling libFlex solves this issue.

**Comment by kef95** [comment]
Can confirm this with `idevicesyslog` from `libimobiledevice`

**Comment by NSExceptional** [comment]
https://github.com/Flipboard/FLEX/issues/397#issuecomment-604146418

Will be made optional in 4.1. I will leave this issue open until I release it

**Comment by NSExceptional** [comment]
4.1.0 adds an option to opt-into the new approach until I can come up with a better fix for getting "just NSLog output" on this screen.
