### ISSUE TITLE
FLEX 4.0 doesn't log NSLog

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#403]
Unfortunately the [new method](https://github.com/Flipboard/FLEX/issues/372#issuecomment-585988013) doesn't work on my device, jailbroken with checkra1n on iOS 13.3.
Was that method tested on iOS 13.3? I've read somewhere that the old syslog [was removed on iOS 13.3](https://twitter.com/anosskirneh/status/1228192596356300800).
I'm not really sure if the tweet refers to os_log_shim_enabled, but the fact is that it doesn't work in my tweaks (compiled using the iOS 13 SDK).

**Comment by NSExceptional** [comment]
4.1.0 adds an option to opt-into the new approach until I can come up with a better fix for getting "just NSLog output" on this screen.
