### ISSUE TITLE
Impossible to copy the description of an object

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#404]
On the latest libFLEX 4.0, it's no longer possible to copy the description of an object (when you tap and hold the description cell).

![55F2E8D8-529C-40B6-88B5-6DB9AA8D095A](https://user-images.githubusercontent.com/60160187/77856907-b32c2980-71fa-11ea-90b6-b99d92dbad27.jpeg)

**Comment by NSExceptional** [comment]
This was moved to the share button in the toolbar
