### ISSUE TITLE
FLEX 4.0 Network history

### ISSUE THREAD

**Issue by DarkoDamjanovic** [Flipboard/FLEX#406]
Hi, 

as we can see the behavior for the Network history changed in 4.0. When we tap on `Response Body` we see now a `NSDictionary`. (which is most of the time not complete because we have quite big responses in our App) FLEX 3.x was showing a plain JSON response here which could be copied and sent. 

This is what we prefer, but it seems gone now? 

What we noticed: tapping on the URL on top (instead of `Response Body`) shows a plain JSON representation but it's not possible to copy and send. Also most of the time the JSON response here is wrong. It seems to be some old cached response... ? 

Showing the plain JSON response in the `Response Body` field is the main FLEX feature for us. Please help us in solving this. We can also debug if you help us in debugging.

Thanks in advance.

Darko

**Comment by NSExceptional** [comment]
Tapping the URL sends a new GET request to that URL, which is why it shows a different response.

Even though the preview is cut off, you should be able to browse the whole response in the dictionary view, for what it's worth. Regardless, I will add a setting to disable this behavior in 4.1. My apologies

**Comment by DarkoDamjanovic** [comment]
There's no need for an apology, we are really happy about this project, thanks for your great work!

But could I ask - which setting to you want to disable? Showing the dictionary instead of the FLEX 3.0 JSON view? (this is what we would prefer)

Thanks.

**Comment by DarkoDamjanovic** [comment]
We need the plain JSON responses all the time as "prove" for the backend team. And also this is a very fast and easy way to create mock data.

**Comment by NSExceptional** [comment]
Yeah, I'm going to add a setting to turn on the dictionary view. So it will default to plain JSON like it was before

**Comment by NSExceptional** [comment]
Fixed in 4.0.0

**Comment by DarkoDamjanovic** [comment]
> Fixed in 4.1.0

Great, thank you!
