### ISSUE TITLE
iPad crash when makeSheet

### ISSUE THREAD

**Issue by viikufa** [Flipboard/FLEX#407]
FLEXAlert
+ (void)makeSheet:(FLEXAlertBuilder)block showFrom:(UIViewController *)viewController

need add check to UIDevice.current.userInterfaceIdiom for iPad https://stackoverflow.com/questions/26039229/swift-uialertcontroller-actionsheet-ipad-ios8-crashes

**Comment by NSExceptional** [comment]
Thank you!

**Comment by NSExceptional** [comment]
Fixed in 4.0.0
