### ISSUE TITLE
duplicate symbol '_rebind_symbols' in:  FLEX/libFLEX.a(flex_fishhook.o)

### ISSUE THREAD

**Issue by boai** [Flipboard/FLEX#408]
duplicate symbol '_rebind_symbols' in:
    /Users/**/Library/Developer/Xcode/DerivedData/**-aqijccxgiqwcgqaelnmggjvzpszk/Build/Products/Debug-iphoneos/FLEX/libFLEX.a(flex_fishhook.o)
    /Users/**/Library/Developer/Xcode/DerivedData/**-aqijccxgiqwcgqaelnmggjvzpszk/Build/Products/Debug-iphoneos/fishhook/libfishhook.a(fishhook.o)
duplicate symbol '_rebind_symbols_image' in:
    /Users/**/Library/Developer/Xcode/DerivedData/**-aqijccxgiqwcgqaelnmggjvzpszk/Build/Products/Debug-iphoneos/FLEX/libFLEX.a(flex_fishhook.o)
    /Users/**/Library/Developer/Xcode/DerivedData/**-aqijccxgiqwcgqaelnmggjvzpszk/Build/Products/Debug-iphoneos/fishhook/libfishhook.a(fishhook.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by boai** [comment]
fishhook 能不能做成依赖库，集成在项目中和其他第三方 冲突了

**Comment by NSExceptional** [comment]
Fixed in 4.1.1
