### ISSUE TITLE
FlexWindow toolbar on top of the keyboard

### ISSUE THREAD

**Issue by flexaddicted** [Flipboard/FLEX#41]
I'm creating a sort of accessibility control and since I like the FlexWindow approach, I'm using a similar technique. Thank you very much for sharing.

A problem arises when the window control (the explorer toolbar) is moved over the area that will be used to display the keyboard. The latter is displayed under the toolbar.

Is this the correct behavior? Thank you in advance.

**Comment by ryanolsonk** [comment]
The system displays the keyboard in a different window (a `UITextEffectsWindow`). You can control the ordering of the windows by setting the `windowLevel` property on your toolbar's window. FLEX intentionally sets its windowLevel to be high to show over things like the keyboard window and the status bar window, but you can change this if you want different behavior in your tool. Take a look at `FLEXWindow.m` for more: https://github.com/Flipboard/FLEX/blob/master/Classes/Explorer%20Toolbar/FLEXWindow.m#L22
