### ISSUE TITLE
Crash when allocating UIViewController classes

### ISSUE THREAD

**Issue by Ram4096** [Flipboard/FLEX#413]
When I try to alloc a class that represents a UIViewController, the app always crashes, with this exception:

```
Exception type: NSInternalInconsistencyException
Reason: <TestViewController: 0x109f304d0> returned nil from -traitCollection, which is not allowed.
Culprit: Unknown
```

I don't know if it's a coincidence or it's the real reason, but this crash persists since FLEX is presented modally.

**Comment by fizix100** [comment]
Me too....

**Comment by NSExceptional** [comment]
Crash log?

**Comment by Ram4096** [comment]
The crash log is available [here](https://pastebin.com/raw/M4pf9sAf). If you need other logs from other apps let me know. I got this on Instagram, trying to alloc the "IGSettingsCategoriesViewController" class (into InstagramAppCoreFramework), but the crash happens every time I try to alloc a UIViewController class (sometimes with the exception about the UITraitCollection)

**Comment by NSExceptional** [comment]
Thank you! Also which version of libFLEX?

**Comment by Ram4096** [comment]
I'm using the latest version available on the Big Boss repository (4.0.0)

**Comment by NSExceptional** [comment]
Tested using a fresh device on 13.4 with the same libflex version, I am unable to reproduce the crash. It sounds like another tweak is causing the crash.

**Comment by Ram4096** [comment]
I've tested this again injecting libFLEX and FLEXing only in the app (setting environmentVariables) and allocating a UIViewController class still crashes, and this time libFLEX and FLEXing are the only tweaks to be injected in the app. 😔

**Comment by NSExceptional** [comment]
Hmmm

Can you post a video? Maybe I’m not doing the right thing. Streamable

**Comment by Ram4096** [comment]
This is the [video](https://streamable.com/p6uu93).
You can see that allocating UIViewController is fine, but allocating any class that has UIViewController as superclass causes the app to crash for me.

In this test libFLEX and FLEXing were the only tweaks to be injected in the app. Other tweaks were not loaded so I'm sure this time that nothing else is the cause.

**Comment by Ram4096** [comment]
I have no crashes anymore, after updating to the recent 4.1.1!
