### ISSUE TITLE
Attempting to view the “Views” panel on SpringBoard causes safe mode

### ISSUE THREAD

**Issue by 23Aaron** [Flipboard/FLEX#416]
This occurs on my iPhone 11, iOS 13.3.

![image](https://user-images.githubusercontent.com/36976487/80010248-0e7fcd80-84c2-11ea-8e38-19ab7ad7c9d7.jpeg)

**Comment by 23Aaron** [comment]
Full crash log available here: https://pastebin.com/bCPYug6f

**Comment by NSExceptional** [comment]
Closing as duplicate of #370

FYI, 3D viewer does not work on springboard

**Comment by 23Aaron** [comment]
This isn’t related to 3D explorer, this happens just trying to click views to see the view hierarchy.

**Comment by NSExceptional** [comment]
I am unable to reproduce this on 13.4. Is it possible another tweak is causing this?

Can you turn off all other tweaks and respring and tell me if the issue persists?

**Comment by 23Aaron** [comment]
Issue is caused by another tweak I have been testing. Disabling it in iCleaner makes the views work again.

**Comment by NSExceptional** [comment]
Does your tweak hook FLEX? If not, I'm curious to find out how it's breaking FLEX. Maybe it is something I can still fix?

**Comment by 23Aaron** [comment]
The tweak I was testing was Scorpion by Esquilli who has since resolved the bug (with your help, I believe)
