### ISSUE TITLE
UISearchDisplayController is deprecated in iOS 8.

### ISSUE THREAD

**Issue by timurbeg** [Flipboard/FLEX#43]
Please update your library for using in iOS 8.

**Comment by ryanolsonk** [comment]
UISearchDisplayController works without issue on iOS 8. The deployment target of this project is currently iOS 6, so we need to continue using UISearchDisplayController. I will look at muting the deprecation warnings around usage of the class.

**Comment by timurbeg** [comment]
Yes, FLEX works on iOS 8, no probs. Only warnings. Thanks, in advance.

**Comment by ryanolsonk** [comment]
I've muted the warnings on master. I'll bump the version momentarily.
