### ISSUE TITLE
There are duplicate requests in the network history list

### ISSUE THREAD

**Issue by Cgema** [Flipboard/FLEX#435]
Hello,  I'd like to submit a question.
while using flex, I found duplicate requests in the network history list.

Give an example,such a web page:
https://market.m.taobao.com/app/dinamic/h5-tb-detail/index.html?miniapp=starbucks&id=614009674697

There is one such request: 
https://h5api.m.taobao.com/h5/mtop.taobao.detail.getdetail/6.0/

In chrome, it looks like this: 
https://gw.alicdn.com/tfs/TB1VoJlM8r0gK0jSZFnXXbRRXXa-2462-1348.jpg

Here's how it works in flex :
https://gw.alicdn.com/tfs/TB17277MND1gK0jSZFsXXbldVXa-1125-2436.png

After refreshing the page, only one request was issued. 
However, it appeared many times in the flex network history list. 

I wonder why?Looking forward to your reply.

**Comment by NSExceptional** [comment]
Hi,

Unless this is your app and you can verify the request is only going out once, it is safe to assume the request is really being sent three times. Notice how the request durations are all unique.

**Comment by Cgema** [comment]
Hi，

This is my own app and web page.
In Chrome and Charles, it only appears once.
But it appears many times in flex.
I noticed that the request duration was different, and found that the request ID was also different after I debugged.
But that doesn't mean it doesn't repeat.

The same problem occurs in other requests on this web page.
I don't know why no one else has submitted this question.

**Comment by NSExceptional** [comment]
Someone else has, but it turned out they were actually just sending the request more than once. This doesn't seem to be a common issue

I will look into this. If you have an example project you can upload which demonstrates the issue that would help tremendously! I am unable to reproduce it on my own.

Also, what iOS version are you running this on?

**Comment by Cgema** [comment]
Hello
It could be a misunderstanding.
After checking with the stand-alone test demo, I found that only one request was sent.
In my app, there may be multiple requests due to rewrite.
This can be used as a case for others to refer to.
Thanks for your help.

**Comment by fabcz** [comment]
> Hello
> It could be a misunderstanding.
> After checking with the stand-alone test demo, I found that only one request was sent.
> In my app, there may be multiple requests due to rewrite.
> This can be used as a case for others to refer to.
> Thanks for your help.

I have a similar situation with my app，The reason is that my app has registered custom NSURLProtocol to monitor the Network like 
```
[NSURLProtocol registerClass:[CustomProtocol class]];
```
You can check to see if your project has similar code

**Comment by Cgema** [comment]
> > Hello
> > It could be a misunderstanding.
> > After checking with the stand-alone test demo, I found that only one request was sent.
> > In my app, there may be multiple requests due to rewrite.
> > This can be used as a case for others to refer to.
> > Thanks for your help.
> 
> I have a similar situation with my app，The reason is that my app has registered custom NSURLProtocol to monitor the Network like
> 
> ```
> [NSURLProtocol registerClass:[CustomProtocol class]];
> ```
> 
> You can check to see if your project has similar code

Very thanks!
Seems to be the reason。
