### ISSUE TITLE
Flex network logger is not working on iOS14 

### ISSUE THREAD

**Issue by MohabTarek** [Flipboard/FLEX#446]
Flex when integrated on any app prior iOS14 is working fine but starting iOS14 the network logger is not collecting any network logs, is there any permission missing that needs to be added or requested ?

**Comment by NSExceptional** [comment]
They probably moved the `resume` method again

**Comment by MohabTarek** [comment]
What does this means? Is it a something in Apple APIs?

**Comment by NSExceptional** [comment]
It means I will fix it when I have time, it's not a big deal

**Comment by aniltaskiran** [comment]
I opened a pr for this issue.
