### ISSUE TITLE
Can FLEX inspect tcp/udp socket , or will be?

### ISSUE THREAD

**Issue by nonstriater** [Flipboard/FLEX#49]

**Comment by ryanolsonk** [comment]
FLEX only knows about network requests that come via NSURLConnection or NSURLSession. If you are using lower level networking APIs, you will not be able to see the requests in FLEX.

**Comment by nin9tyfour** [comment]
This could be implemented with https://github.com/facebook/fishhook if someone is willing to dump the dyld shared cache, open the associated frameworks and rebind the symbols. It'd be a huge undertaking though. I am also not so sure as to how FLEX actually is injected, I do believe that fishhook needed to rebound the associated symbols before UIApplicationMain, but I am not certain.

**Comment by nonstriater** [comment]
@nin9tyfour  great,It's a nice way to my problem,i'll try it
