### ISSUE TITLE
type encoding issue

### ISSUE THREAD

**Issue by DaidoujiChen** [Flipboard/FLEX#52]
Hello @ryanolsonk,

I found some type encoding is `@?`. Than the method `readableTypeForEncoding` in `FLEXRuntimeUtility.m` convert this to `(? *)` like
![ios simulator screen shot 2015 3 13 11 31 35](https://cloud.githubusercontent.com/assets/670441/6641505/1df2f408-c9d9-11e4-98e6-0fc3fa5608b9.png)

I am not sure but maybe all of them just `id` type?

**Comment by ryanolsonk** [comment]
Hey @DaidoujiChen 

The `?` type encoding means "unknown type" (see https://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html)

It looks like the the original type encoding in this case was `^?`, or pointer to unknown type. Have you seen this on any methods that exist in public headers? I'm guessing the parameter is some kind of block.

**Comment by DaidoujiChen** [comment]
Hello @ryanolsonk,

The original type encoding in this case is `@?` not `^?`.

	// Objects
	if (encodingCString[0] == '@') {
	 	NSString *class = [encodingString substringFromIndex:1];
	 	class = [class stringByReplacingOccurrencesOfString:@"\"" withString:@""];
	 	if ([class length] == 0) {
	 		class = @"id";
	 	} else {
	 		class = [class stringByAppendingString:@" *"];
	 	}
	 	return class;
	 }
	 
`@?` -> `(? *)` wrong!

`@"UIView"` -> `(UIView *)` correct!

Yes, `(? *)` also found in public method like `transitionFromView:toView:duration:options:completion:`
![ios simulator screen shot 2015 3 14 9 44 52](https://cloud.githubusercontent.com/assets/670441/6649803/89a2e806-ca2f-11e4-97a7-ff8972b8f414.png)

I refer to https://github.com/JaviSoto/iOS8-Runtime-Headers, it seems like declared `@?` to `id` type.

**Comment by ryanolsonk** [comment]
Ah, sorry, I missed that. Thanks for clarifying. Seems like the best thing to do here is to make the check for id `[class length] == 0 || [class isEqual:@"?"] `. Does that seem right to you?

**Comment by DaidoujiChen** [comment]
YES！

**Comment by ryanolsonk** [comment]
Finally made this change (48826e2160db73e8ad5b2a14d901293e1e55edeb). Thanks for finding it @DaidoujiChen.

**Comment by DaidoujiChen** [comment]
:+1:  thanks @ryanolsonk
