### ISSUE TITLE
Can't turn off shouldEnableOnLaunch

### ISSUE THREAD

**Issue by coppercash** [Flipboard/FLEX#56]
FLEX is really helpful, thanks for your brilliant work!

But I believe the `@YES` in following code should be `shouldEnableOnLaunch `, right?

``` objc
+ (void)setShouldEnableOnLaunch:(BOOL)shouldEnableOnLaunch
{
    [[NSUserDefaults standardUserDefaults] setObject:@YES forKey:kFLEXNetworkObserverEnableOnLaunchDefaultsKey];
}
```

**Comment by ryanolsonk** [comment]
![picard-facepalm](https://cloud.githubusercontent.com/assets/1422245/6947341/61e2315c-d85b-11e4-861b-0ec876582da1.jpg)

Thanks for catching this! Fixed in efab76025325ba1eff5e2be9735972ccfd7e045d
