### ISSUE TITLE
cocoalumberjack support

### ISSUE THREAD

**Issue by shams-ahmed** [Flipboard/FLEX#58]
is there a way to present cocoalumberjack output in system log? 

https://github.com/CocoaLumberjack/CocoaLumberjack

**Comment by raphaelschaad** [comment]
You could start by looking at how [FLAnimatedImage does it](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImageDemo/FLAnimatedImage/FLAnimatedImage.h#L102), but it's quite challenging to make it work automagically in all scenarios and it has been a source of build/configuration errors.

**Comment by ryanolsonk** [comment]
I think the question is asking about the system log debugging interface in FLEX. You can add the ASL as a Cocoa Lumberjack logger to see your `DDLog*` messages in FLEX:

```objc
[DDLog addLogger:[DDASLLogger sharedInstance]];
```

Let me know if I've understood the question correctly.

**Comment by shams-ahmed** [comment]
@ryanolsonk that correct, i'll like cocoalumberjack console output to be presented in Flex system log... i'll try your approach

**Comment by ryanolsonk** [comment]
Great. Closing this issue for now.
