### ISSUE TITLE
Invoke UIAlertView show method lead to crash.

### ISSUE THREAD

**Issue by simalone** [Flipboard/FLEX#59]
Crash at line:  [alert show];
supportedInterfaceOrientations method in FLEXExplorerViewController is called circularly.

![image](https://cloud.githubusercontent.com/assets/700749/7135043/6069179e-e2d5-11e4-883d-fae03141bc5e.png)

**Comment by ryanolsonk** [comment]
Thanks for reporting this. I'm looking for potential solutions now. I believe this is limited to builds using 8.3 SDK.

**Comment by studentdeng** [comment]
on iOS8.3 if we use UIAlertView it will cause this problem

**Comment by ryanolsonk** [comment]
This is now fixed (c38b90ee60d2ea9131a01b3e1a7014848e0494c9). Thanks again for reporting.
