### ISSUE TITLE
[!] Unable to find a specification for `Flex` when using cocoapods

### ISSUE THREAD

**Issue by williamFalcon** [Flipboard/FLEX#66]
On the latest cocoapods version (0.37.1), cocoapods generates the following error when doing pod install :``` [!] Unable to find a specification for `Flex`   ```

To replicate:
1. Update cocoapods to 0.37.1    
2. ```pod install```

**Comment by ryanolsonk** [comment]
What is the line in your podfile? Perhaps CocoaPods is now case sensitive. The name of the pod is `'FLEX'`.

If changing the case doesn't help, I suggest you open an issue with CocoaPods. The FLEX spec does show up in CocoaPods search: https://cocoapods.org/?q=flex

**Comment by williamFalcon** [comment]
The line is 'Flex'. I'll check to see it 'FLEX' fixes it.
