### ISSUE TITLE
[Suggestion] Adding Activator support

### ISSUE THREAD

**Issue by scj643** [Flipboard/FLEX#72]
This would make it so you can use an activator gesture to toggle the picker.

**Comment by ryanolsonk** [comment]
Thanks for the suggestion. I'm not familiar with Activator. Are there any examples or documentation that you can point me towards?

**Comment by scj643** [comment]
Oh this is for if flex was to be made into a mobile substrate tweak for jailbroken devices

**Comment by ryanolsonk** [comment]
There are other projects that support FLEX injection with substrate (e.g. https://github.com/dtrukr/FLEX_injected). Those repos are probably a better place for this feature suggestion.
