### ISSUE TITLE
Killswitch

### ISSUE THREAD

**Issue by j4ckhaal** [Flipboard/FLEX#79]
To toggle it on/off in all apps at once

**Comment by ryanolsonk** [comment]
This project is not associated with the jailbreak tweaks that allow you to inject into other apps. https://github.com/dtrukr/FLEX_injected may be a better project for this suggestion.

**Comment by j4ckhaal** [comment]
Hey, I meant toggling the pop up with which you can select elements on and off for all apps, instead of having to turn it off individually for each app I turned it on for.

**Comment by ryanolsonk** [comment]
Sorry, I'm not sure what you're referring to. Can you post a screenshot the pop up you're talking about?

**Comment by j4ckhaal** [comment]
Nvm
