### ISSUE TITLE
update FLEXExplorerViewController.m

### ISSUE THREAD

**Issue by LOLLYPO** [Flipboard/FLEX#83]
i used `pod 'FLEX', '~> 2.0', :configurations => ['Debug']`

at method `supportedInterfaceOrientations`
it will be show a warn about conflict return type
it returns `UIInterfaceOrientationMask` but uiviewcontroller return `NSUInteger`,this is the reason

a Obsessive-compulsive disorder person's isses,3q

**Comment by ryanolsonk** [comment]
Are you able to update to Xcode 7 and the iOS 9 SDK? The return type was changed in iOS 9, so older versions of the SDK now get the warning. I suppose we could wrap this in `#pragma clang diagnostic ignored` to accommodate building with older versions of the SDK.

**Comment by LOLLYPO** [comment]
oh.i used Xcode 6.4.thank you

**Comment by LOLLYPO** [comment]
if someone has problem same with me,you can use my solution or update your Xcode to 7 
the method i used to disable this warn is:
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wmismatched-return-types"
- (UIInterfaceOrientationMask)supportedInterfaceOrientations{
#pragma clang diagnostic pop
```
