### ISSUE TITLE
crash due to KVO

### ISSUE THREAD

**Issue by fjswhl** [Flipboard/FLEX#86]
crash reason:
Fatal Exception: NSRangeException
Cannot remove an observer <FLEXExplorerViewController> for the key path "frame" from <TTTLogoutWindow> because it is not registered as an observer.

Here is trace:
Thread : Fatal Exception: NSRangeException
0  CoreFoundation                 6490509128 **exceptionPreprocess
1  libobjc.A.dylib                6838321024 objc_exception_throw
2  CoreFoundation                 6490508944 -[NSException initWithCoder:]
3  Foundation                     6505732568 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:]
4  Foundation                     6505731252 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:]
5  TutorTeacher                   4297117164 -[FLEXExplorerViewController stopObservingView:](FLEXExplorerViewController.m:308)
6  TutorTeacher                   4297114184 -[FLEXExplorerViewController setViewsAtTapPoint:](FLEXExplorerViewController.m:240)
7  TutorTeacher                   4297127036 -[FLEXExplorerViewController updateOutlineViewsForSelectionPoint:](FLEXExplorerViewController.m:547)
8  TutorTeacher                   4297126852 -[FLEXExplorerViewController handleSelectionTap:](FLEXExplorerViewController.m:538)
9  UIKit                          6585987888 _UIGestureRecognizerSendTargetActions
10 UIKit                          6581963612 _UIGestureRecognizerSendActions
11 UIKit                          6580447324 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:]
12 UIKit                          6585992972 ___UIGestureRecognizerUpdate_block_invoke898
13 UIKit                          6580181176 _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks
14 UIKit                          6580168252 _UIGestureRecognizerUpdate
15 UIKit                          6580438732 -[UIWindow _sendGesturesForEvent:]
16 UIKit                          6580436168 -[UIWindow sendEvent:]
17 UIKit                          6580241572 -[UIApplication sendEvent:]
18 UIKit                          6580234092 _UIApplicationHandleEventQueue
19 CoreFoundation                 6490211652 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION**
20 CoreFoundation                 6490210264 __CFRunLoopDoSources0
21 CoreFoundation                 6490201304 __CFRunLoopRun
22 CoreFoundation                 6489345184 CFRunLoopRunSpecific
23 GraphicsServices               6676234376 GSEventRunModal
24 UIKit                          6580670460 UIApplicationMain
25 TutorTeacher                   4297150244 main (main.m:14)
26 libdyld.dylib                  6847031480 start

**Comment by ryanolsonk** [comment]
Thanks for the report. Does this consistently repro for you or was it a one-off crash? I'm having trouble reproducing the crash in the example project, and I don't see anything obviously wrong with the KVO accounting, so I'm not exactly sure what's happening here.
