### ISSUE TITLE
cannot activate FLEX with shortcut f

### ISSUE THREAD

**Issue by AnsonYao** [Flipboard/FLEX#90]
Settings:
The project is with swift 2.1 in Xcode 7. I installed FLEX with cocoapod ~> 2.0 so it should be the newest version. 

Problem description:
When app is running In the simulator, when pressed "f" in the keyboard of my computer, the toolbar does not show up. But it can be activated with code ''FLEXManager.sharedManager().showExplorer()''

**Comment by ryanolsonk** [comment]
Can you verify that the version of FLEX you're using has the `FLEXKeyboardShortcutManager` class and that `FLEXManager.sharedManager().simulatorShortcutsEnabled` is `true`?

**Comment by ryanolsonk** [comment]
Closing since I can't reproduce this. Please comment here if you continue to see the issue.

**Comment by bigface** [comment]
Sorry for the late reply.

I have added

FLEXManager.sharedManager().simulatorShortcutsEnabled = true

and have checked FLEXKeyboardShortcutManager  is in the pod.

But I still cannot use the keyboard shortcut...


My pod file:
pod 'FLEX', '~> 2.0', :configurations => ['Debug']

**Comment by bigface** [comment]
The project is with swift and newest version of XCode Version 7.2 (7C68).

**Comment by AnsonYao** [comment]
Sorry guys. Turns out I probably forget to choose "connect hareware keyboard" option for the simulator.
