### ISSUE TITLE
Support search view hierarchy by its pointer address to help resolve auto layout runtime conflict.

### ISSUE THREAD

**Issue by untouchable741** [Flipboard/FLEX#95]
When we have to build a complex view with a lot of components on it with tons of layout constraint. Although we resolved all the constraint warning on xib/storyboard but on runtime we still sometime got breaking constraint due to layout conflict and got these error logs.
```
(
    "<NSLayoutConstraint:0x15dd2e20 H:[UITextField:0x15dbe780]-(NSSpace(20))-|   (Names: '|':UIView:0x15dc4f90 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x15de1ee0 h=--& v=--& UIView:0x15dbe780.midX ==>",
    "<NSAutoresizingMaskLayoutConstraint:0x15de22d0 h=--& v=--& H:[UIView:0x15dbe780(0)]>",
    "<NSAutoresizingMaskLayoutConstraint:0x13a9eda0 h=--& v=--& H:[UIView:0x15dc4f90(320)]>"
)
```
Its a bit hard to find out which view has that conflict constraint because we have only its pointer address, such as (0x15dc4f90, 0x15dbe780, ..)
Therefore i'm thinking of adding support to search for its pointer address inside FLEXHierarchyTableViewController.
![Image of Yaktocat]
(https://i.imgur.com/fzGdgUV.png)
So you can easily filter the view with its pointer address then tap on it and locate it on the screen to resolved the conflict easier.
I think it wont be messed up with title searching because the pointer address is a HexString, its different to UIKit component class name.
I made a pull request for it here:
https://github.com/Flipboard/FLEX/pull/94

Thanks

**Comment by untouchable741** [comment]
It has been merged. 
Thanks @ryanolsonk

**Comment by ryanolsonk** [comment]
:+1: Thanks for the pull request! Closing this now.
