### ISSUE TITLE
Resolve UISearchDisplayController deprecation warnings

### ISSUE THREAD

**Issue by timonus** [Flipboard/FLEX#96]
![screen shot 2015-12-08 at 12 47 51 pm](https://cloud.githubusercontent.com/assets/522951/11668052/ffb87efe-9da9-11e5-94df-200c715e3202.png)

**Comment by ryanolsonk** [comment]
Resolved in dda9dd5beb2c69f3613f0f5194717a0e9c7f99e2, 888887f09a78e8889975fc0515e7b675e564b74a, and b70a1a2f485118a3c0b97848f1294bc8b5df1c2f

**Comment by timonus** [comment]
:+1: thanks!
