### ISSUE TITLE
Make FLEXExplorerViewController more configurable

### ISSUE THREAD

**Issue by ryanolsonk** [Flipboard/FLEX#98]
The inheritance patterns used in the FLEXExplorerViewController subclasses are pretty nasty. Ideally we can make FLEXExplorerViewController more configurable and remove these subclasses. This should make it easier to configure the explorer for more classes of objects.

**Comment by NSExceptional** [comment]
Closing bc I have this mostly done in my 4.0 branch 😎 It's completely customizable now
